// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.album.defs
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

//! Generated bindings for the `app.rocksky.album` Lexicon namespace/module.
pub mod get_album;
pub mod get_album_tracks;
pub mod get_albums;

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::blob::BlobRef;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime, UriValue};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{lexicon, IntoStatic};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

use crate::app_rocksky::song::SongViewBasic;
#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Deserialize, Serialize};
/// A declaration of an album.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "app.rocksky.album",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Album<S: BosStr = DefaultStr> {
    ///The album art of the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub album_art: Option<BlobRef<S>>,
    ///The URL of the album art of the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub album_art_url: Option<UriValue<S>>,
    ///The Apple Music link of the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub apple_music_link: Option<UriValue<S>>,
    ///The artist of the album.
    pub artist: S,
    ///The date and time when the album was created.
    pub created_at: Datetime,
    ///The duration of the album in milliseconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration: Option<i64>,
    ///The genre of the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub genre: Option<S>,
    ///The release date of the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub release_date: Option<Datetime>,
    ///The Spotify link of the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub spotify_link: Option<UriValue<S>>,
    ///The tags of the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<S>>,
    ///The tidal link of the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tidal_link: Option<UriValue<S>>,
    ///The title of the album.
    pub title: S,
    ///The year the album was released.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub year: Option<i64>,
    ///The YouTube link of the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub youtube_link: Option<UriValue<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct AlbumGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Album<S>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct AlbumViewBasic<S: BosStr = DefaultStr> {
    ///The URL of the album art image.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub album_art: Option<UriValue<S>>,
    ///The artist of the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub artist: Option<S>,
    ///The URI of the album's artist.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub artist_uri: Option<AtUri<S>>,
    ///The unique identifier of the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<S>,
    ///The number of times the album has been played.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub play_count: Option<i64>,
    ///The release date of the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub release_date: Option<S>,
    ///The SHA256 hash of the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sha256: Option<S>,
    ///The title of the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<S>,
    ///The number of unique listeners who have played the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unique_listeners: Option<i64>,
    ///The URI of the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uri: Option<AtUri<S>>,
    ///The year the album was released.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub year: Option<i64>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct AlbumViewDetailed<S: BosStr = DefaultStr> {
    ///The URL of the album art image.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub album_art: Option<UriValue<S>>,
    ///The artist of the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub artist: Option<S>,
    ///The URI of the album's artist.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub artist_uri: Option<AtUri<S>>,
    ///The unique identifier of the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<S>,
    ///The number of times the album has been played.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub play_count: Option<i64>,
    ///The release date of the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub release_date: Option<S>,
    ///The SHA256 hash of the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sha256: Option<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<S>>,
    ///The title of the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tracks: Option<Vec<SongViewBasic<S>>>,
    ///The number of unique listeners who have played the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unique_listeners: Option<i64>,
    ///The URI of the album.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uri: Option<AtUri<S>>,
    ///The year the album was released.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub year: Option<i64>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

impl<S: BosStr> Album<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, AlbumRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct AlbumRecord;
impl XrpcResp for AlbumRecord {
    const NSID: &'static str = "app.rocksky.album";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = AlbumGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<AlbumGetRecordOutput<S>> for Album<S> {
    fn from(output: AlbumGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Album<S> {
    const NSID: &'static str = "app.rocksky.album";
    type Record = AlbumRecord;
}

impl Collection for AlbumRecord {
    const NSID: &'static str = "app.rocksky.album";
    type Record = AlbumRecord;
}

impl<S: BosStr> LexiconSchema for Album<S> {
    fn nsid() -> &'static str {
        "app.rocksky.album"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_app_rocksky_album()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.album_art {
            {
                let size = value.blob().size;
                if size > 2000000usize {
                    return Err(ConstraintError::BlobTooLarge {
                        path: ValidationPath::from_field("album_art"),
                        max: 2000000usize,
                        actual: size,
                    });
                }
            }
        }
        if let Some(ref value) = self.album_art {
            {
                let mime = value.blob().mime_type.as_str();
                let accepted: &[&str] = &["image/png", "image/jpeg"];
                let matched = accepted.iter().any(|pattern| {
                    if *pattern == "*/*" {
                        true
                    } else if pattern.ends_with("/*") {
                        let prefix = &pattern[..pattern.len() - 2];
                        mime.starts_with(prefix) && mime.as_bytes().get(prefix.len()) == Some(&b'/')
                    } else {
                        mime == *pattern
                    }
                });
                if !matched {
                    return Err(ConstraintError::BlobMimeTypeNotAccepted {
                        path: ValidationPath::from_field("album_art"),
                        accepted: vec!["image/png".to_string(), "image/jpeg".to_string()],
                        actual: mime.to_string(),
                    });
                }
            }
        }
        {
            let value = &self.artist;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 256usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("artist"),
                    max: 256usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.artist;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) < 1usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("artist"),
                    min: 1usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.genre {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 256usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("genre"),
                    max: 256usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.title;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 512usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("title"),
                    max: 512usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.title;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) < 1usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("title"),
                    min: 1usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

impl<S: BosStr> LexiconSchema for AlbumViewBasic<S> {
    fn nsid() -> &'static str {
        "app.rocksky.album.defs"
    }
    fn def_name() -> &'static str {
        "albumViewBasic"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_app_rocksky_album_defs()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.play_count {
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("play_count"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.unique_listeners {
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("unique_listeners"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

impl<S: BosStr> LexiconSchema for AlbumViewDetailed<S> {
    fn nsid() -> &'static str {
        "app.rocksky.album.defs"
    }
    fn def_name() -> &'static str {
        "albumViewDetailed"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_app_rocksky_album_defs()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.play_count {
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("play_count"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.unique_listeners {
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("unique_listeners"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

pub mod album_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Artist;
        type CreatedAt;
        type Title;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Artist = Unset;
        type CreatedAt = Unset;
        type Title = Unset;
    }
    ///State transition - sets the `artist` field to Set
    pub struct SetArtist<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetArtist<St> {}
    impl<St: State> State for SetArtist<St> {
        type Artist = Set<members::artist>;
        type CreatedAt = St::CreatedAt;
        type Title = St::Title;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCreatedAt<St> {}
    impl<St: State> State for SetCreatedAt<St> {
        type Artist = St::Artist;
        type CreatedAt = Set<members::created_at>;
        type Title = St::Title;
    }
    ///State transition - sets the `title` field to Set
    pub struct SetTitle<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetTitle<St> {}
    impl<St: State> State for SetTitle<St> {
        type Artist = St::Artist;
        type CreatedAt = St::CreatedAt;
        type Title = Set<members::title>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `artist` field
        pub struct artist(());
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `title` field
        pub struct title(());
    }
}

/// Builder for constructing an instance of this type.
pub struct AlbumBuilder<St: album_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<BlobRef<S>>,
        Option<UriValue<S>>,
        Option<UriValue<S>>,
        Option<S>,
        Option<Datetime>,
        Option<i64>,
        Option<S>,
        Option<Datetime>,
        Option<UriValue<S>>,
        Option<Vec<S>>,
        Option<UriValue<S>>,
        Option<S>,
        Option<i64>,
        Option<UriValue<S>>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl Album<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> AlbumBuilder<album_state::Empty, DefaultStr> {
        AlbumBuilder::new()
    }
}

impl<S: BosStr> Album<S> {
    /// Create a new builder for this type
    pub fn builder() -> AlbumBuilder<album_state::Empty, S> {
        AlbumBuilder::builder()
    }
}

impl AlbumBuilder<album_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        AlbumBuilder {
            _state: PhantomData,
            _fields: (
                None, None, None, None, None, None, None, None, None, None, None, None, None, None,
            ),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> AlbumBuilder<album_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        AlbumBuilder {
            _state: PhantomData,
            _fields: (
                None, None, None, None, None, None, None, None, None, None, None, None, None, None,
            ),
            _type: PhantomData,
        }
    }
}

impl<St: album_state::State, S: BosStr> AlbumBuilder<St, S> {
    /// Set the `albumArt` field (optional)
    pub fn album_art(mut self, value: impl Into<Option<BlobRef<S>>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `albumArt` field to an Option value (optional)
    pub fn maybe_album_art(mut self, value: Option<BlobRef<S>>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St: album_state::State, S: BosStr> AlbumBuilder<St, S> {
    /// Set the `albumArtUrl` field (optional)
    pub fn album_art_url(mut self, value: impl Into<Option<UriValue<S>>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `albumArtUrl` field to an Option value (optional)
    pub fn maybe_album_art_url(mut self, value: Option<UriValue<S>>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St: album_state::State, S: BosStr> AlbumBuilder<St, S> {
    /// Set the `appleMusicLink` field (optional)
    pub fn apple_music_link(mut self, value: impl Into<Option<UriValue<S>>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `appleMusicLink` field to an Option value (optional)
    pub fn maybe_apple_music_link(mut self, value: Option<UriValue<S>>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St, S: BosStr> AlbumBuilder<St, S>
where
    St: album_state::State,
    St::Artist: album_state::IsUnset,
{
    /// Set the `artist` field (required)
    pub fn artist(mut self, value: impl Into<S>) -> AlbumBuilder<album_state::SetArtist<St>, S> {
        self._fields.3 = Option::Some(value.into());
        AlbumBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> AlbumBuilder<St, S>
where
    St: album_state::State,
    St::CreatedAt: album_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> AlbumBuilder<album_state::SetCreatedAt<St>, S> {
        self._fields.4 = Option::Some(value.into());
        AlbumBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: album_state::State, S: BosStr> AlbumBuilder<St, S> {
    /// Set the `duration` field (optional)
    pub fn duration(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.5 = value.into();
        self
    }
    /// Set the `duration` field to an Option value (optional)
    pub fn maybe_duration(mut self, value: Option<i64>) -> Self {
        self._fields.5 = value;
        self
    }
}

impl<St: album_state::State, S: BosStr> AlbumBuilder<St, S> {
    /// Set the `genre` field (optional)
    pub fn genre(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.6 = value.into();
        self
    }
    /// Set the `genre` field to an Option value (optional)
    pub fn maybe_genre(mut self, value: Option<S>) -> Self {
        self._fields.6 = value;
        self
    }
}

impl<St: album_state::State, S: BosStr> AlbumBuilder<St, S> {
    /// Set the `releaseDate` field (optional)
    pub fn release_date(mut self, value: impl Into<Option<Datetime>>) -> Self {
        self._fields.7 = value.into();
        self
    }
    /// Set the `releaseDate` field to an Option value (optional)
    pub fn maybe_release_date(mut self, value: Option<Datetime>) -> Self {
        self._fields.7 = value;
        self
    }
}

impl<St: album_state::State, S: BosStr> AlbumBuilder<St, S> {
    /// Set the `spotifyLink` field (optional)
    pub fn spotify_link(mut self, value: impl Into<Option<UriValue<S>>>) -> Self {
        self._fields.8 = value.into();
        self
    }
    /// Set the `spotifyLink` field to an Option value (optional)
    pub fn maybe_spotify_link(mut self, value: Option<UriValue<S>>) -> Self {
        self._fields.8 = value;
        self
    }
}

impl<St: album_state::State, S: BosStr> AlbumBuilder<St, S> {
    /// Set the `tags` field (optional)
    pub fn tags(mut self, value: impl Into<Option<Vec<S>>>) -> Self {
        self._fields.9 = value.into();
        self
    }
    /// Set the `tags` field to an Option value (optional)
    pub fn maybe_tags(mut self, value: Option<Vec<S>>) -> Self {
        self._fields.9 = value;
        self
    }
}

impl<St: album_state::State, S: BosStr> AlbumBuilder<St, S> {
    /// Set the `tidalLink` field (optional)
    pub fn tidal_link(mut self, value: impl Into<Option<UriValue<S>>>) -> Self {
        self._fields.10 = value.into();
        self
    }
    /// Set the `tidalLink` field to an Option value (optional)
    pub fn maybe_tidal_link(mut self, value: Option<UriValue<S>>) -> Self {
        self._fields.10 = value;
        self
    }
}

impl<St, S: BosStr> AlbumBuilder<St, S>
where
    St: album_state::State,
    St::Title: album_state::IsUnset,
{
    /// Set the `title` field (required)
    pub fn title(mut self, value: impl Into<S>) -> AlbumBuilder<album_state::SetTitle<St>, S> {
        self._fields.11 = Option::Some(value.into());
        AlbumBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: album_state::State, S: BosStr> AlbumBuilder<St, S> {
    /// Set the `year` field (optional)
    pub fn year(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.12 = value.into();
        self
    }
    /// Set the `year` field to an Option value (optional)
    pub fn maybe_year(mut self, value: Option<i64>) -> Self {
        self._fields.12 = value;
        self
    }
}

impl<St: album_state::State, S: BosStr> AlbumBuilder<St, S> {
    /// Set the `youtubeLink` field (optional)
    pub fn youtube_link(mut self, value: impl Into<Option<UriValue<S>>>) -> Self {
        self._fields.13 = value.into();
        self
    }
    /// Set the `youtubeLink` field to an Option value (optional)
    pub fn maybe_youtube_link(mut self, value: Option<UriValue<S>>) -> Self {
        self._fields.13 = value;
        self
    }
}

impl<St, S: BosStr> AlbumBuilder<St, S>
where
    St: album_state::State,
    St::Artist: album_state::IsSet,
    St::CreatedAt: album_state::IsSet,
    St::Title: album_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Album<S> {
        Album {
            album_art: self._fields.0,
            album_art_url: self._fields.1,
            apple_music_link: self._fields.2,
            artist: self._fields.3.unwrap(),
            created_at: self._fields.4.unwrap(),
            duration: self._fields.5,
            genre: self._fields.6,
            release_date: self._fields.7,
            spotify_link: self._fields.8,
            tags: self._fields.9,
            tidal_link: self._fields.10,
            title: self._fields.11.unwrap(),
            year: self._fields.12,
            youtube_link: self._fields.13,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Album<S> {
        Album {
            album_art: self._fields.0,
            album_art_url: self._fields.1,
            apple_music_link: self._fields.2,
            artist: self._fields.3.unwrap(),
            created_at: self._fields.4.unwrap(),
            duration: self._fields.5,
            genre: self._fields.6,
            release_date: self._fields.7,
            spotify_link: self._fields.8,
            tags: self._fields.9,
            tidal_link: self._fields.10,
            title: self._fields.11.unwrap(),
            year: self._fields.12,
            youtube_link: self._fields.13,
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_app_rocksky_album() -> LexiconDoc<'static> {
    use alloc::collections::BTreeMap;
    #[allow(unused_imports)]
    use jacquard_common::{deps::smol_str::SmolStr, types::blob::MimeType, CowStr};
    use jacquard_lexicon::lexicon::*;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("app.rocksky.album"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(CowStr::new_static("A declaration of an album.")),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(vec![
                            SmolStr::new_static("title"),
                            SmolStr::new_static("artist"),
                            SmolStr::new_static("createdAt"),
                        ]),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("albumArt"),
                                LexObjectProperty::Blob(LexBlob {
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("albumArtUrl"),
                                LexObjectProperty::String(LexString {
                                    description: Some(CowStr::new_static(
                                        "The URL of the album art of the album.",
                                    )),
                                    format: Some(LexStringFormat::Uri),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("appleMusicLink"),
                                LexObjectProperty::String(LexString {
                                    description: Some(CowStr::new_static(
                                        "The Apple Music link of the album.",
                                    )),
                                    format: Some(LexStringFormat::Uri),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("artist"),
                                LexObjectProperty::String(LexString {
                                    description: Some(CowStr::new_static(
                                        "The artist of the album.",
                                    )),
                                    min_length: Some(1usize),
                                    max_length: Some(256usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    description: Some(CowStr::new_static(
                                        "The date and time when the album was created.",
                                    )),
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("duration"),
                                LexObjectProperty::Integer(LexInteger {
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("genre"),
                                LexObjectProperty::String(LexString {
                                    description: Some(CowStr::new_static(
                                        "The genre of the album.",
                                    )),
                                    max_length: Some(256usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("releaseDate"),
                                LexObjectProperty::String(LexString {
                                    description: Some(CowStr::new_static(
                                        "The release date of the album.",
                                    )),
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("spotifyLink"),
                                LexObjectProperty::String(LexString {
                                    description: Some(CowStr::new_static(
                                        "The Spotify link of the album.",
                                    )),
                                    format: Some(LexStringFormat::Uri),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("tags"),
                                LexObjectProperty::Array(LexArray {
                                    description: Some(CowStr::new_static("The tags of the album.")),
                                    items: LexArrayItem::String(LexString {
                                        min_length: Some(1usize),
                                        max_length: Some(256usize),
                                        ..Default::default()
                                    }),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("tidalLink"),
                                LexObjectProperty::String(LexString {
                                    description: Some(CowStr::new_static(
                                        "The tidal link of the album.",
                                    )),
                                    format: Some(LexStringFormat::Uri),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("title"),
                                LexObjectProperty::String(LexString {
                                    description: Some(CowStr::new_static(
                                        "The title of the album.",
                                    )),
                                    min_length: Some(1usize),
                                    max_length: Some(512usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("year"),
                                LexObjectProperty::Integer(LexInteger {
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("youtubeLink"),
                                LexObjectProperty::String(LexString {
                                    description: Some(CowStr::new_static(
                                        "The YouTube link of the album.",
                                    )),
                                    format: Some(LexStringFormat::Uri),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}

fn lexicon_doc_app_rocksky_album_defs() -> LexiconDoc<'static> {
    use alloc::collections::BTreeMap;
    #[allow(unused_imports)]
    use jacquard_common::{deps::smol_str::SmolStr, types::blob::MimeType, CowStr};
    use jacquard_lexicon::lexicon::*;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("app.rocksky.album.defs"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("albumViewBasic"),
                LexUserType::Object(LexObject {
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("albumArt"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "The URL of the album art image.",
                                )),
                                format: Some(LexStringFormat::Uri),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("artist"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static("The artist of the album.")),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("artistUri"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "The URI of the album's artist.",
                                )),
                                format: Some(LexStringFormat::AtUri),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("id"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "The unique identifier of the album.",
                                )),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("playCount"),
                            LexObjectProperty::Integer(LexInteger {
                                minimum: Some(0i64),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("releaseDate"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "The release date of the album.",
                                )),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("sha256"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "The SHA256 hash of the album.",
                                )),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("title"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static("The title of the album.")),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("uniqueListeners"),
                            LexObjectProperty::Integer(LexInteger {
                                minimum: Some(0i64),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("uri"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static("The URI of the album.")),
                                format: Some(LexStringFormat::AtUri),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("year"),
                            LexObjectProperty::Integer(LexInteger {
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("albumViewDetailed"),
                LexUserType::Object(LexObject {
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("albumArt"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "The URL of the album art image.",
                                )),
                                format: Some(LexStringFormat::Uri),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("artist"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static("The artist of the album.")),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("artistUri"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "The URI of the album's artist.",
                                )),
                                format: Some(LexStringFormat::AtUri),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("id"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "The unique identifier of the album.",
                                )),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("playCount"),
                            LexObjectProperty::Integer(LexInteger {
                                minimum: Some(0i64),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("releaseDate"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "The release date of the album.",
                                )),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("sha256"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "The SHA256 hash of the album.",
                                )),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("tags"),
                            LexObjectProperty::Array(LexArray {
                                items: LexArrayItem::String(LexString {
                                    ..Default::default()
                                }),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("title"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static("The title of the album.")),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("tracks"),
                            LexObjectProperty::Array(LexArray {
                                items: LexArrayItem::Ref(LexRef {
                                    r#ref: CowStr::new_static(
                                        "app.rocksky.song.defs#songViewBasic",
                                    ),
                                    ..Default::default()
                                }),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("uniqueListeners"),
                            LexObjectProperty::Integer(LexInteger {
                                minimum: Some(0i64),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("uri"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static("The URI of the album.")),
                                format: Some(LexStringFormat::AtUri),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("year"),
                            LexObjectProperty::Integer(LexInteger {
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}
