// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.notification.defs
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

//! Generated bindings for the `app.rocksky.notification` Lexicon namespace/module.
pub mod get_unread_count;
pub mod list_notifications;
pub mod update_seen;

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::ident::AtIdentifier;
use jacquard_common::types::string::{Datetime, Did, UriValue};
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

use crate::app_rocksky::notification;
#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Deserialize, Serialize};
/// The user who triggered a notification.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct NotificationActor<S: BosStr = DefaultStr> {
    ///The URL of the actor's avatar image.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub avatar: Option<UriValue<S>>,
    ///The decentralized identifier of the actor.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub did: Option<Did<S>>,
    ///The display name of the actor.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub display_name: Option<S>,
    ///The handle of the actor.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<AtIdentifier<S>>,
    ///The unique identifier of the actor.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct NotificationView<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor: Option<notification::NotificationActor<S>>,
    ///When the notification was created.
    pub created_at: Datetime,
    ///The unique identifier of the notification.
    pub id: S,
    ///Whether the notification has been viewed.
    pub read: bool,
    ///The content of the related shout, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub shout_content: Option<S>,
    ///The id of the related shout, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub shout_id: Option<S>,
    ///The at-uri of the subject the notification relates to.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subject_uri: Option<S>,
    ///The notification type: like_scrobble, follow, comment_scrobble, comment_profile, reply, or react_comment.
    pub r#type: NotificationViewType<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// The notification type: like_scrobble, follow, comment_scrobble, comment_profile, reply, or react_comment.

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum NotificationViewType<S: BosStr = DefaultStr> {
    LikeScrobble,
    Follow,
    CommentScrobble,
    CommentProfile,
    Reply,
    ReactComment,
    Other(S),
}

impl<S: BosStr> NotificationViewType<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::LikeScrobble => "like_scrobble",
            Self::Follow => "follow",
            Self::CommentScrobble => "comment_scrobble",
            Self::CommentProfile => "comment_profile",
            Self::Reply => "reply",
            Self::ReactComment => "react_comment",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "like_scrobble" => Self::LikeScrobble,
            "follow" => Self::Follow,
            "comment_scrobble" => Self::CommentScrobble,
            "comment_profile" => Self::CommentProfile,
            "reply" => Self::Reply,
            "react_comment" => Self::ReactComment,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for NotificationViewType<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for NotificationViewType<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for NotificationViewType<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for NotificationViewType<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for NotificationViewType<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for NotificationViewType<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = NotificationViewType<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            NotificationViewType::LikeScrobble => NotificationViewType::LikeScrobble,
            NotificationViewType::Follow => NotificationViewType::Follow,
            NotificationViewType::CommentScrobble => NotificationViewType::CommentScrobble,
            NotificationViewType::CommentProfile => NotificationViewType::CommentProfile,
            NotificationViewType::Reply => NotificationViewType::Reply,
            NotificationViewType::ReactComment => NotificationViewType::ReactComment,
            NotificationViewType::Other(v) => NotificationViewType::Other(v.into_static()),
        }
    }
}

impl<S: BosStr> LexiconSchema for NotificationActor<S> {
    fn nsid() -> &'static str {
        "app.rocksky.notification.defs"
    }
    fn def_name() -> &'static str {
        "notificationActor"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_app_rocksky_notification_defs()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

impl<S: BosStr> LexiconSchema for NotificationView<S> {
    fn nsid() -> &'static str {
        "app.rocksky.notification.defs"
    }
    fn def_name() -> &'static str {
        "notificationView"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_app_rocksky_notification_defs()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

fn lexicon_doc_app_rocksky_notification_defs() -> LexiconDoc<'static> {
    use alloc::collections::BTreeMap;
    #[allow(unused_imports)]
    use jacquard_common::{deps::smol_str::SmolStr, types::blob::MimeType, CowStr};
    use jacquard_lexicon::lexicon::*;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("app.rocksky.notification.defs"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("notificationActor"),
                LexUserType::Object(LexObject {
                    description: Some(CowStr::new_static("The user who triggered a notification.")),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("avatar"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "The URL of the actor's avatar image.",
                                )),
                                format: Some(LexStringFormat::Uri),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("did"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "The decentralized identifier of the actor.",
                                )),
                                format: Some(LexStringFormat::Did),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("displayName"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "The display name of the actor.",
                                )),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("handle"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static("The handle of the actor.")),
                                format: Some(LexStringFormat::AtIdentifier),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("id"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "The unique identifier of the actor.",
                                )),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("notificationView"),
                LexUserType::Object(LexObject {
                    required: Some(
                        vec![
                            SmolStr::new_static("id"), SmolStr::new_static("type"),
                            SmolStr::new_static("read"), SmolStr::new_static("createdAt")
                        ],
                    ),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("actor"),
                            LexObjectProperty::Ref(LexRef {
                                r#ref: CowStr::new_static(
                                    "app.rocksky.notification.defs#notificationActor",
                                ),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("createdAt"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static("When the notification was created."),
                                ),
                                format: Some(LexStringFormat::Datetime),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("id"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "The unique identifier of the notification.",
                                    ),
                                ),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("read"),
                            LexObjectProperty::Boolean(LexBoolean {
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("shoutContent"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "The content of the related shout, if any.",
                                    ),
                                ),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("shoutId"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static("The id of the related shout, if any."),
                                ),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("subjectUri"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "The at-uri of the subject the notification relates to.",
                                    ),
                                ),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("type"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "The notification type: like_scrobble, follow, comment_scrobble, comment_profile, reply, or react_comment.",
                                    ),
                                ),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}

pub mod notification_view_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type CreatedAt;
        type Id;
        type Read;
        type Type;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type CreatedAt = Unset;
        type Id = Unset;
        type Read = Unset;
        type Type = Unset;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCreatedAt<St> {}
    impl<St: State> State for SetCreatedAt<St> {
        type CreatedAt = Set<members::created_at>;
        type Id = St::Id;
        type Read = St::Read;
        type Type = St::Type;
    }
    ///State transition - sets the `id` field to Set
    pub struct SetId<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetId<St> {}
    impl<St: State> State for SetId<St> {
        type CreatedAt = St::CreatedAt;
        type Id = Set<members::id>;
        type Read = St::Read;
        type Type = St::Type;
    }
    ///State transition - sets the `read` field to Set
    pub struct SetRead<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetRead<St> {}
    impl<St: State> State for SetRead<St> {
        type CreatedAt = St::CreatedAt;
        type Id = St::Id;
        type Read = Set<members::read>;
        type Type = St::Type;
    }
    ///State transition - sets the `type` field to Set
    pub struct SetType<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetType<St> {}
    impl<St: State> State for SetType<St> {
        type CreatedAt = St::CreatedAt;
        type Id = St::Id;
        type Read = St::Read;
        type Type = Set<members::r#type>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `id` field
        pub struct id(());
        ///Marker type for the `read` field
        pub struct read(());
        ///Marker type for the `type` field
        pub struct r#type(());
    }
}

/// Builder for constructing an instance of this type.
pub struct NotificationViewBuilder<St: notification_view_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<notification::NotificationActor<S>>,
        Option<Datetime>,
        Option<S>,
        Option<bool>,
        Option<S>,
        Option<S>,
        Option<S>,
        Option<NotificationViewType<S>>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl NotificationView<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> NotificationViewBuilder<notification_view_state::Empty, DefaultStr> {
        NotificationViewBuilder::new()
    }
}

impl<S: BosStr> NotificationView<S> {
    /// Create a new builder for this type
    pub fn builder() -> NotificationViewBuilder<notification_view_state::Empty, S> {
        NotificationViewBuilder::builder()
    }
}

impl NotificationViewBuilder<notification_view_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        NotificationViewBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> NotificationViewBuilder<notification_view_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        NotificationViewBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: notification_view_state::State, S: BosStr> NotificationViewBuilder<St, S> {
    /// Set the `actor` field (optional)
    pub fn actor(mut self, value: impl Into<Option<notification::NotificationActor<S>>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `actor` field to an Option value (optional)
    pub fn maybe_actor(mut self, value: Option<notification::NotificationActor<S>>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St, S: BosStr> NotificationViewBuilder<St, S>
where
    St: notification_view_state::State,
    St::CreatedAt: notification_view_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> NotificationViewBuilder<notification_view_state::SetCreatedAt<St>, S> {
        self._fields.1 = Option::Some(value.into());
        NotificationViewBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> NotificationViewBuilder<St, S>
where
    St: notification_view_state::State,
    St::Id: notification_view_state::IsUnset,
{
    /// Set the `id` field (required)
    pub fn id(
        mut self,
        value: impl Into<S>,
    ) -> NotificationViewBuilder<notification_view_state::SetId<St>, S> {
        self._fields.2 = Option::Some(value.into());
        NotificationViewBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> NotificationViewBuilder<St, S>
where
    St: notification_view_state::State,
    St::Read: notification_view_state::IsUnset,
{
    /// Set the `read` field (required)
    pub fn read(
        mut self,
        value: impl Into<bool>,
    ) -> NotificationViewBuilder<notification_view_state::SetRead<St>, S> {
        self._fields.3 = Option::Some(value.into());
        NotificationViewBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: notification_view_state::State, S: BosStr> NotificationViewBuilder<St, S> {
    /// Set the `shoutContent` field (optional)
    pub fn shout_content(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.4 = value.into();
        self
    }
    /// Set the `shoutContent` field to an Option value (optional)
    pub fn maybe_shout_content(mut self, value: Option<S>) -> Self {
        self._fields.4 = value;
        self
    }
}

impl<St: notification_view_state::State, S: BosStr> NotificationViewBuilder<St, S> {
    /// Set the `shoutId` field (optional)
    pub fn shout_id(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.5 = value.into();
        self
    }
    /// Set the `shoutId` field to an Option value (optional)
    pub fn maybe_shout_id(mut self, value: Option<S>) -> Self {
        self._fields.5 = value;
        self
    }
}

impl<St: notification_view_state::State, S: BosStr> NotificationViewBuilder<St, S> {
    /// Set the `subjectUri` field (optional)
    pub fn subject_uri(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.6 = value.into();
        self
    }
    /// Set the `subjectUri` field to an Option value (optional)
    pub fn maybe_subject_uri(mut self, value: Option<S>) -> Self {
        self._fields.6 = value;
        self
    }
}

impl<St, S: BosStr> NotificationViewBuilder<St, S>
where
    St: notification_view_state::State,
    St::Type: notification_view_state::IsUnset,
{
    /// Set the `type` field (required)
    pub fn r#type(
        mut self,
        value: impl Into<NotificationViewType<S>>,
    ) -> NotificationViewBuilder<notification_view_state::SetType<St>, S> {
        self._fields.7 = Option::Some(value.into());
        NotificationViewBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> NotificationViewBuilder<St, S>
where
    St: notification_view_state::State,
    St::CreatedAt: notification_view_state::IsSet,
    St::Id: notification_view_state::IsSet,
    St::Read: notification_view_state::IsSet,
    St::Type: notification_view_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> NotificationView<S> {
        NotificationView {
            actor: self._fields.0,
            created_at: self._fields.1.unwrap(),
            id: self._fields.2.unwrap(),
            read: self._fields.3.unwrap(),
            shout_content: self._fields.4,
            shout_id: self._fields.5,
            subject_uri: self._fields.6,
            r#type: self._fields.7.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> NotificationView<S> {
        NotificationView {
            actor: self._fields.0,
            created_at: self._fields.1.unwrap(),
            id: self._fields.2.unwrap(),
            read: self._fields.3.unwrap(),
            shout_content: self._fields.4,
            shout_id: self._fields.5,
            subject_uri: self._fields.6,
            r#type: self._fields.7.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}
