// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.playlistItem
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{lexicon, IntoStatic};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

use crate::app_rocksky::song::SongViewBasic;
use crate::com_atproto::repo::strong_ref::StrongRef;
#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Deserialize, Serialize};
/// A playlist item represents a single entry in a playlist, containing metadata and references to media content.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "app.rocksky.playlistItem",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct PlaylistItem<S: BosStr = DefaultStr> {
    ///The date the playlist was created.
    pub created_at: Datetime,
    ///The order of the item in the playlist.
    pub order: i64,
    pub subject: StrongRef<S>,
    pub track: SongViewBasic<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct PlaylistItemGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: PlaylistItem<S>,
}

impl<S: BosStr> PlaylistItem<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, PlaylistItemRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct PlaylistItemRecord;
impl XrpcResp for PlaylistItemRecord {
    const NSID: &'static str = "app.rocksky.playlistItem";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = PlaylistItemGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<PlaylistItemGetRecordOutput<S>> for PlaylistItem<S> {
    fn from(output: PlaylistItemGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for PlaylistItem<S> {
    const NSID: &'static str = "app.rocksky.playlistItem";
    type Record = PlaylistItemRecord;
}

impl Collection for PlaylistItemRecord {
    const NSID: &'static str = "app.rocksky.playlistItem";
    type Record = PlaylistItemRecord;
}

impl<S: BosStr> LexiconSchema for PlaylistItem<S> {
    fn nsid() -> &'static str {
        "app.rocksky.playlistItem"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_app_rocksky_playlistItem()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.order;
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("order"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

pub mod playlist_item_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type CreatedAt;
        type Order;
        type Subject;
        type Track;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type CreatedAt = Unset;
        type Order = Unset;
        type Subject = Unset;
        type Track = Unset;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCreatedAt<St> {}
    impl<St: State> State for SetCreatedAt<St> {
        type CreatedAt = Set<members::created_at>;
        type Order = St::Order;
        type Subject = St::Subject;
        type Track = St::Track;
    }
    ///State transition - sets the `order` field to Set
    pub struct SetOrder<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetOrder<St> {}
    impl<St: State> State for SetOrder<St> {
        type CreatedAt = St::CreatedAt;
        type Order = Set<members::order>;
        type Subject = St::Subject;
        type Track = St::Track;
    }
    ///State transition - sets the `subject` field to Set
    pub struct SetSubject<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetSubject<St> {}
    impl<St: State> State for SetSubject<St> {
        type CreatedAt = St::CreatedAt;
        type Order = St::Order;
        type Subject = Set<members::subject>;
        type Track = St::Track;
    }
    ///State transition - sets the `track` field to Set
    pub struct SetTrack<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetTrack<St> {}
    impl<St: State> State for SetTrack<St> {
        type CreatedAt = St::CreatedAt;
        type Order = St::Order;
        type Subject = St::Subject;
        type Track = Set<members::track>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `order` field
        pub struct order(());
        ///Marker type for the `subject` field
        pub struct subject(());
        ///Marker type for the `track` field
        pub struct track(());
    }
}

/// Builder for constructing an instance of this type.
pub struct PlaylistItemBuilder<St: playlist_item_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<Datetime>,
        Option<i64>,
        Option<StrongRef<S>>,
        Option<SongViewBasic<S>>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl PlaylistItem<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> PlaylistItemBuilder<playlist_item_state::Empty, DefaultStr> {
        PlaylistItemBuilder::new()
    }
}

impl<S: BosStr> PlaylistItem<S> {
    /// Create a new builder for this type
    pub fn builder() -> PlaylistItemBuilder<playlist_item_state::Empty, S> {
        PlaylistItemBuilder::builder()
    }
}

impl PlaylistItemBuilder<playlist_item_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        PlaylistItemBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> PlaylistItemBuilder<playlist_item_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        PlaylistItemBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> PlaylistItemBuilder<St, S>
where
    St: playlist_item_state::State,
    St::CreatedAt: playlist_item_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> PlaylistItemBuilder<playlist_item_state::SetCreatedAt<St>, S> {
        self._fields.0 = Option::Some(value.into());
        PlaylistItemBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> PlaylistItemBuilder<St, S>
where
    St: playlist_item_state::State,
    St::Order: playlist_item_state::IsUnset,
{
    /// Set the `order` field (required)
    pub fn order(
        mut self,
        value: impl Into<i64>,
    ) -> PlaylistItemBuilder<playlist_item_state::SetOrder<St>, S> {
        self._fields.1 = Option::Some(value.into());
        PlaylistItemBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> PlaylistItemBuilder<St, S>
where
    St: playlist_item_state::State,
    St::Subject: playlist_item_state::IsUnset,
{
    /// Set the `subject` field (required)
    pub fn subject(
        mut self,
        value: impl Into<StrongRef<S>>,
    ) -> PlaylistItemBuilder<playlist_item_state::SetSubject<St>, S> {
        self._fields.2 = Option::Some(value.into());
        PlaylistItemBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> PlaylistItemBuilder<St, S>
where
    St: playlist_item_state::State,
    St::Track: playlist_item_state::IsUnset,
{
    /// Set the `track` field (required)
    pub fn track(
        mut self,
        value: impl Into<SongViewBasic<S>>,
    ) -> PlaylistItemBuilder<playlist_item_state::SetTrack<St>, S> {
        self._fields.3 = Option::Some(value.into());
        PlaylistItemBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> PlaylistItemBuilder<St, S>
where
    St: playlist_item_state::State,
    St::CreatedAt: playlist_item_state::IsSet,
    St::Order: playlist_item_state::IsSet,
    St::Subject: playlist_item_state::IsSet,
    St::Track: playlist_item_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> PlaylistItem<S> {
        PlaylistItem {
            created_at: self._fields.0.unwrap(),
            order: self._fields.1.unwrap(),
            subject: self._fields.2.unwrap(),
            track: self._fields.3.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> PlaylistItem<S> {
        PlaylistItem {
            created_at: self._fields.0.unwrap(),
            order: self._fields.1.unwrap(),
            subject: self._fields.2.unwrap(),
            track: self._fields.3.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_app_rocksky_playlistItem() -> LexiconDoc<'static> {
    use alloc::collections::BTreeMap;
    #[allow(unused_imports)]
    use jacquard_common::{deps::smol_str::SmolStr, types::blob::MimeType, CowStr};
    use jacquard_lexicon::lexicon::*;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("app.rocksky.playlistItem"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "A playlist item represents a single entry in a playlist, containing metadata and references to media content.",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("createdAt"),
                                SmolStr::new_static("track"), SmolStr::new_static("order"),
                                SmolStr::new_static("subject")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static("The date the playlist was created."),
                                    ),
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("order"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(0i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("subject"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("com.atproto.repo.strongRef"),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("track"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static(
                                        "app.rocksky.song.defs#songViewBasic",
                                    ),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}
