// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.song.getSongRecentListeners
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::app_rocksky::song::RecentListenerView;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::AtUri;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetSongRecentListeners<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
    pub uri: AtUri<S>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetSongRecentListenersOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub listeners: Option<Vec<RecentListenerView<S>>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.rocksky.song.getSongRecentListeners` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetSongRecentListenersOutput<S>` for this endpoint.*/
pub struct GetSongRecentListenersResponse;
impl jacquard_common::xrpc::XrpcResp for GetSongRecentListenersResponse {
    const NSID: &'static str = "app.rocksky.song.getSongRecentListeners";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetSongRecentListenersOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetSongRecentListeners<S> {
    const NSID: &'static str = "app.rocksky.song.getSongRecentListeners";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetSongRecentListenersResponse;
}

/** Endpoint marker for the `app.rocksky.song.getSongRecentListeners` query.

Path: `/xrpc/app.rocksky.song.getSongRecentListeners`. The request payload type is `GetSongRecentListeners<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetSongRecentListenersRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetSongRecentListenersRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.song.getSongRecentListeners";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetSongRecentListeners<S>;
    type Response = GetSongRecentListenersResponse;
}

pub mod get_song_recent_listeners_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Uri;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Uri = Unset;
    }
    ///State transition - sets the `uri` field to Set
    pub struct SetUri<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetUri<St> {}
    impl<St: State> State for SetUri<St> {
        type Uri = Set<members::uri>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `uri` field
        pub struct uri(());
    }
}

/// Builder for constructing an instance of this type.
pub struct GetSongRecentListenersBuilder<
    St: get_song_recent_listeners_state::State,
    S: BosStr = DefaultStr,
> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<i64>, Option<i64>, Option<AtUri<S>>),
    _type: PhantomData<fn() -> S>,
}

impl GetSongRecentListeners<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GetSongRecentListenersBuilder<get_song_recent_listeners_state::Empty, DefaultStr>
    {
        GetSongRecentListenersBuilder::new()
    }
}

impl<S: BosStr> GetSongRecentListeners<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetSongRecentListenersBuilder<get_song_recent_listeners_state::Empty, S> {
        GetSongRecentListenersBuilder::builder()
    }
}

impl GetSongRecentListenersBuilder<get_song_recent_listeners_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetSongRecentListenersBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GetSongRecentListenersBuilder<get_song_recent_listeners_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetSongRecentListenersBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: get_song_recent_listeners_state::State, S: BosStr> GetSongRecentListenersBuilder<St, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St: get_song_recent_listeners_state::State, S: BosStr> GetSongRecentListenersBuilder<St, S> {
    /// Set the `offset` field (optional)
    pub fn offset(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `offset` field to an Option value (optional)
    pub fn maybe_offset(mut self, value: Option<i64>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St, S: BosStr> GetSongRecentListenersBuilder<St, S>
where
    St: get_song_recent_listeners_state::State,
    St::Uri: get_song_recent_listeners_state::IsUnset,
{
    /// Set the `uri` field (required)
    pub fn uri(
        mut self,
        value: impl Into<AtUri<S>>,
    ) -> GetSongRecentListenersBuilder<get_song_recent_listeners_state::SetUri<St>, S> {
        self._fields.2 = Option::Some(value.into());
        GetSongRecentListenersBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetSongRecentListenersBuilder<St, S>
where
    St: get_song_recent_listeners_state::State,
    St::Uri: get_song_recent_listeners_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> GetSongRecentListeners<S> {
        GetSongRecentListeners {
            limit: self._fields.0,
            offset: self._fields.1,
            uri: self._fields.2.unwrap(),
        }
    }
}
