// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.song.matchSong
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::app_rocksky::song::SongViewDetailed;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct MatchSong<S: BosStr = DefaultStr> {
    pub artist: S,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub isrc: Option<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mb_id: Option<S>,
    pub title: S,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct MatchSongOutput<S: BosStr = DefaultStr> {
    #[serde(flatten)]
    pub value: SongViewDetailed<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.rocksky.song.matchSong` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `MatchSongOutput<S>` for this endpoint.*/
pub struct MatchSongResponse;
impl jacquard_common::xrpc::XrpcResp for MatchSongResponse {
    const NSID: &'static str = "app.rocksky.song.matchSong";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = MatchSongOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for MatchSong<S> {
    const NSID: &'static str = "app.rocksky.song.matchSong";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = MatchSongResponse;
}

/** Endpoint marker for the `app.rocksky.song.matchSong` query.

Path: `/xrpc/app.rocksky.song.matchSong`. The request payload type is `MatchSong<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct MatchSongRequest;
impl jacquard_common::xrpc::XrpcEndpoint for MatchSongRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.song.matchSong";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = MatchSong<S>;
    type Response = MatchSongResponse;
}

pub mod match_song_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Artist;
        type Title;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Artist = Unset;
        type Title = Unset;
    }
    ///State transition - sets the `artist` field to Set
    pub struct SetArtist<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetArtist<St> {}
    impl<St: State> State for SetArtist<St> {
        type Artist = Set<members::artist>;
        type Title = St::Title;
    }
    ///State transition - sets the `title` field to Set
    pub struct SetTitle<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetTitle<St> {}
    impl<St: State> State for SetTitle<St> {
        type Artist = St::Artist;
        type Title = Set<members::title>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `artist` field
        pub struct artist(());
        ///Marker type for the `title` field
        pub struct title(());
    }
}

/// Builder for constructing an instance of this type.
pub struct MatchSongBuilder<St: match_song_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>, Option<S>, Option<S>, Option<S>),
    _type: PhantomData<fn() -> S>,
}

impl MatchSong<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> MatchSongBuilder<match_song_state::Empty, DefaultStr> {
        MatchSongBuilder::new()
    }
}

impl<S: BosStr> MatchSong<S> {
    /// Create a new builder for this type
    pub fn builder() -> MatchSongBuilder<match_song_state::Empty, S> {
        MatchSongBuilder::builder()
    }
}

impl MatchSongBuilder<match_song_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        MatchSongBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> MatchSongBuilder<match_song_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        MatchSongBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> MatchSongBuilder<St, S>
where
    St: match_song_state::State,
    St::Artist: match_song_state::IsUnset,
{
    /// Set the `artist` field (required)
    pub fn artist(
        mut self,
        value: impl Into<S>,
    ) -> MatchSongBuilder<match_song_state::SetArtist<St>, S> {
        self._fields.0 = Option::Some(value.into());
        MatchSongBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: match_song_state::State, S: BosStr> MatchSongBuilder<St, S> {
    /// Set the `isrc` field (optional)
    pub fn isrc(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `isrc` field to an Option value (optional)
    pub fn maybe_isrc(mut self, value: Option<S>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St: match_song_state::State, S: BosStr> MatchSongBuilder<St, S> {
    /// Set the `mbId` field (optional)
    pub fn mb_id(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `mbId` field to an Option value (optional)
    pub fn maybe_mb_id(mut self, value: Option<S>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St, S: BosStr> MatchSongBuilder<St, S>
where
    St: match_song_state::State,
    St::Title: match_song_state::IsUnset,
{
    /// Set the `title` field (required)
    pub fn title(
        mut self,
        value: impl Into<S>,
    ) -> MatchSongBuilder<match_song_state::SetTitle<St>, S> {
        self._fields.3 = Option::Some(value.into());
        MatchSongBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> MatchSongBuilder<St, S>
where
    St: match_song_state::State,
    St::Artist: match_song_state::IsSet,
    St::Title: match_song_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> MatchSong<S> {
        MatchSong {
            artist: self._fields.0.unwrap(),
            isrc: self._fields.1,
            mb_id: self._fields.2,
            title: self._fields.3.unwrap(),
        }
    }
}
