// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.rockbox.getAudioSettings
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::app_rocksky::rockbox::SettingsView;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::ident::AtIdentifier;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetAudioSettings<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub did: Option<AtIdentifier<S>>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetAudioSettingsOutput<S: BosStr = DefaultStr> {
    #[serde(flatten)]
    pub value: SettingsView<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.rocksky.rockbox.getAudioSettings` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetAudioSettingsOutput<S>` for this endpoint.*/
pub struct GetAudioSettingsResponse;
impl jacquard_common::xrpc::XrpcResp for GetAudioSettingsResponse {
    const NSID: &'static str = "app.rocksky.rockbox.getAudioSettings";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetAudioSettingsOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetAudioSettings<S> {
    const NSID: &'static str = "app.rocksky.rockbox.getAudioSettings";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetAudioSettingsResponse;
}

/** Endpoint marker for the `app.rocksky.rockbox.getAudioSettings` query.

Path: `/xrpc/app.rocksky.rockbox.getAudioSettings`. The request payload type is `GetAudioSettings<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetAudioSettingsRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetAudioSettingsRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.rockbox.getAudioSettings";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetAudioSettings<S>;
    type Response = GetAudioSettingsResponse;
}

pub mod get_audio_settings_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type.
pub struct GetAudioSettingsBuilder<St: get_audio_settings_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<AtIdentifier<S>>,),
    _type: PhantomData<fn() -> S>,
}

impl GetAudioSettings<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GetAudioSettingsBuilder<get_audio_settings_state::Empty, DefaultStr> {
        GetAudioSettingsBuilder::new()
    }
}

impl<S: BosStr> GetAudioSettings<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetAudioSettingsBuilder<get_audio_settings_state::Empty, S> {
        GetAudioSettingsBuilder::builder()
    }
}

impl GetAudioSettingsBuilder<get_audio_settings_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetAudioSettingsBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GetAudioSettingsBuilder<get_audio_settings_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetAudioSettingsBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<St: get_audio_settings_state::State, S: BosStr> GetAudioSettingsBuilder<St, S> {
    /// Set the `did` field (optional)
    pub fn did(mut self, value: impl Into<Option<AtIdentifier<S>>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `did` field to an Option value (optional)
    pub fn maybe_did(mut self, value: Option<AtIdentifier<S>>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St, S: BosStr> GetAudioSettingsBuilder<St, S>
where
    St: get_audio_settings_state::State,
{
    /// Build the final struct.
    pub fn build(self) -> GetAudioSettings<S> {
        GetAudioSettings {
            did: self._fields.0,
        }
    }
}
