// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.rockbox.putAudioSettings
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::app_rocksky::rockbox::CrossfadeSettings;
use crate::app_rocksky::rockbox::EqualizerSettings;
use crate::app_rocksky::rockbox::ReplayGainSettings;
use crate::app_rocksky::rockbox::SettingsView;
use crate::app_rocksky::rockbox::ToneSettings;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct PutAudioSettings<S: BosStr = DefaultStr> {
    ///Crossfade settings to apply.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub crossfade: Option<CrossfadeSettings<S>>,
    ///Equalizer settings to apply.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub equalizer: Option<EqualizerSettings<S>>,
    ///Replay gain settings to apply.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub replay_gain: Option<ReplayGainSettings<S>>,
    ///Tone control settings to apply.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tone: Option<ToneSettings<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct PutAudioSettingsOutput<S: BosStr = DefaultStr> {
    #[serde(flatten)]
    pub value: SettingsView<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.rocksky.rockbox.putAudioSettings` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `PutAudioSettingsOutput<S>` for this endpoint.*/
pub struct PutAudioSettingsResponse;
impl jacquard_common::xrpc::XrpcResp for PutAudioSettingsResponse {
    const NSID: &'static str = "app.rocksky.rockbox.putAudioSettings";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = PutAudioSettingsOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for PutAudioSettings<S> {
    const NSID: &'static str = "app.rocksky.rockbox.putAudioSettings";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Response = PutAudioSettingsResponse;
}

/** Endpoint marker for the `app.rocksky.rockbox.putAudioSettings` procedure.

Path: `/xrpc/app.rocksky.rockbox.putAudioSettings`. The request payload type is `PutAudioSettings<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct PutAudioSettingsRequest;
impl jacquard_common::xrpc::XrpcEndpoint for PutAudioSettingsRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.rockbox.putAudioSettings";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Request<S: BosStr> = PutAudioSettings<S>;
    type Response = PutAudioSettingsResponse;
}
