// @generated by jacquard-lexicon. DO NOT EDIT.
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

//! Generated bindings for the `app.rocksky` Lexicon namespace/module.
pub mod actor;
pub mod album;
pub mod apikey;
pub mod artist;
pub mod charts;
pub mod dropbox;
pub mod feed;
pub mod googledrive;
pub mod graph;
pub mod library;
pub mod like;
pub mod mirror;
pub mod player;
pub mod playlist;
pub mod playlist_item;
pub mod radio;
pub mod rockbox;
pub mod scrobble;
pub mod shout;
pub mod song;
pub mod spotify;
pub mod stats;
