//! # rocksky-sdk
//!
//! The official Rust SDK for [Rocksky](https://rocksky.app) — a music scrobbling
//! & discovery platform built on the [AT Protocol](https://atproto.com), on top
//! of [jacquard](https://crates.io/crates/jacquard).
//!
//! The design mirrors Bluesky's [`@atproto/api`](https://github.com/bluesky-social/atproto/tree/main/packages/api):
//! a [`RockskyAgent`] wraps a jacquard session and exposes both high-level
//! convenience verbs (`scrobble`, `like`, `follow`, `shout`, `set_now_playing`)
//! and a typed namespace escape hatch. Reads go through the unauthenticated
//! [`AppView`] client.
//!
//! ```no_run
//! # async fn demo() -> rocksky_sdk::Result<()> {
//! use rocksky_sdk::{RockskyAgent, ScrobbleDraft};
//!
//! let agent = RockskyAgent::builder()
//!     .session_store("~/.config/rocksky/session.json")
//!     .build()?;
//! agent.login_password("alice.bsky.social", "app-password").await?;
//!
//! agent
//!     .scrobble(&ScrobbleDraft {
//!         title: "Chaser".into(),
//!         artist: "Calibro 35".into(),
//!         album: "Jazzploitation".into(),
//!         album_artist: "Calibro 35".into(),
//!         duration_ms: 182_320,
//!         ..Default::default()
//!     })
//!     .await?;
//!
//! let recent = agent.appview().scrobbles("alice.bsky.social", 25, 0).await?;
//! # let _ = recent;
//! # Ok(())
//! # }
//! ```
//!
//! The typed `app.rocksky.*` records live in [`app_rocksky`] (also re-exported as
//! [`lexicons`]); they are generated by `jacquard-codegen` from
//! `apps/api/lexicons/` (see `scripts/gen-lexicons.sh`).

#![forbid(unsafe_code)]

// The generated lexicon code targets `no_std`-style paths (`alloc::…`).
extern crate alloc;

// --- generated from apps/api/lexicons (see scripts/gen-lexicons.sh) ---
// These modules live at the crate root because the generated code refers to
// them as `crate::app_rocksky` / `crate::com_atproto` / `crate::app_bsky` /
// `crate::builder_types` — keep the names so regenerated output drops in
// without edits.
#[allow(unused_imports, dead_code, non_snake_case, clippy::all)]
pub mod app_bsky;
#[allow(unused_imports, dead_code, non_snake_case, clippy::all)]
pub mod app_rocksky;
#[allow(unused_imports, dead_code, non_snake_case, clippy::all)]
pub mod builder_types;
#[allow(unused_imports, dead_code, non_snake_case, clippy::all)]
pub mod com_atproto;

/// The generated `app.rocksky.*` lexicon bindings, under the documented name.
pub use crate::app_rocksky as lexicons;

// --- hand-written SDK modules ---
pub mod agent;
pub mod appview;
pub mod auth;
pub mod dedup;
pub mod error;
pub mod facets;
#[cfg(feature = "jetstream")]
pub mod jetstream;
pub mod namespaces;

pub use agent::{
    AlbumDraft, ArtistDraft, NowPlaying, RockskyAgent, RockskyAgentBuilder, ScrobbleDraft,
    ScrobbleResult, SongDraft,
};
pub use appview::AppView;
pub use auth::Profile;
#[cfg(feature = "dedup")]
pub use dedup::{IndexStats, RepoIndex};
pub use error::{Result, SdkError};
#[cfg(feature = "jetstream")]
pub use jetstream::JetstreamConfig;

/// The default public AppView base URL.
pub const DEFAULT_APPVIEW: &str = "https://api.rocksky.app";
