// @generated by jacquard-lexicon. DO NOT EDIT.
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

//! Generated bindings for the `community.lexicon.calendar` Lexicon namespace/module.
pub mod event;
pub mod rsvp;
