//! Embeds the built web UI into the binary.
//!
//! Looks for `apps/web/dist` (or `$ROCKSKY_WEB_DIST`) and generates a table of
//! `include_bytes!` entries that `src/web.rs` serves as a single-page app. The
//! dist is *optional*: with no build present the table is empty and the binary
//! still runs the API, answering `/` with a page that says how to build the UI.
//! That keeps `cargo build` working in a fresh checkout where `bun run build`
//! has never been run.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));

    println!("cargo:rerun-if-env-changed=ROCKSKY_WEB_DIST");

    let dist = match std::env::var_os("ROCKSKY_WEB_DIST") {
        Some(dir) => PathBuf::from(dir),
        // crates/appview -> repo root -> apps/web/dist
        None => manifest_dir.join("../../apps/web/dist"),
    };

    let files = if dist.is_dir() {
        // Re-run when the build output changes. Watching the directory itself
        // catches added and removed files; individual files are watched below
        // so a rebuilt asset is picked up too.
        println!("cargo:rerun-if-changed={}", dist.display());
        collect(&dist)
    } else {
        println!(
            "cargo:warning=no web UI found at {} — the binary will serve the API only. \
             Build it with `bun run build` in apps/web, or set ROCKSKY_WEB_DIST.",
            dist.display()
        );
        BTreeMap::new()
    };

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs. DO NOT EDIT.\n");
    let _ = writeln!(generated, "pub static ASSETS: &[Asset] = &[");

    for (route, absolute) in &files {
        println!("cargo:rerun-if-changed={}", absolute.display());
        let _ = writeln!(
            generated,
            "    Asset {{ path: {route:?}, content_type: {:?}, bytes: include_bytes!({:?}) }},",
            content_type(route),
            absolute,
        );
    }

    let _ = writeln!(generated, "];");

    std::fs::write(out_dir.join("web_assets.rs"), generated).expect("write web_assets.rs");
}

/// Maps every file under `dist` to the path it is served at, e.g.
/// `dist/assets/index-abc.js` -> `assets/index-abc.js`.
fn collect(dist: &Path) -> BTreeMap<String, PathBuf> {
    let mut files = BTreeMap::new();
    walk(dist, dist, &mut files);
    files
}

fn walk(root: &Path, dir: &Path, files: &mut BTreeMap<String, PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };

    for entry in entries.flatten() {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().to_string();

        // Skip `.DS_Store` and friends: OS cruft that would otherwise be
        // baked into the binary and served.
        if name.starts_with('.') {
            continue;
        }

        if path.is_dir() {
            walk(root, &path, files);
            continue;
        }

        if let Ok(relative) = path.strip_prefix(root) {
            // Always forward slashes: this becomes a URL path, not a file path.
            let route = relative
                .components()
                .map(|component| component.as_os_str().to_string_lossy())
                .collect::<Vec<_>>()
                .join("/");
            if let Ok(absolute) = path.canonicalize() {
                files.insert(route, absolute);
            }
        }
    }
}

fn content_type(route: &str) -> &'static str {
    let extension = route.rsplit_once('.').map(|(_, ext)| ext).unwrap_or("");
    match extension {
        "html" => "text/html; charset=utf-8",
        "js" | "mjs" => "text/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "json" => "application/json",
        "webmanifest" => "application/manifest+json",
        "map" => "application/json",
        "svg" => "image/svg+xml",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "gif" => "image/gif",
        "webp" => "image/webp",
        "avif" => "image/avif",
        "ico" => "image/x-icon",
        "woff" => "font/woff",
        "woff2" => "font/woff2",
        "ttf" => "font/ttf",
        "otf" => "font/otf",
        "wasm" => "application/wasm",
        "txt" => "text/plain; charset=utf-8",
        "xml" => "application/xml",
        "mp3" => "audio/mpeg",
        "ogg" => "audio/ogg",
        "flac" => "audio/flac",
        _ => "application/octet-stream",
    }
}
