// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.mirror.putMirrorSource
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::app_rocksky::mirror::MirrorSourceView;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct PutMirrorSource<S: BosStr = DefaultStr> {
    ///API key / token to be encrypted at rest. Omit to leave the existing key unchanged. Pass an empty string to clear it.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub api_key: Option<S>,
    ///Enable or disable mirroring for this provider.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    ///External username (Last.fm / ListenBrainz). Required when enabling those providers. Ignored for Teal.fm.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub external_username: Option<S>,
    ///One of: lastfm, listenbrainz, tealfm
    pub provider: S,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct PutMirrorSourceOutput<S: BosStr = DefaultStr> {
    #[serde(flatten)]
    pub value: MirrorSourceView<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.rocksky.mirror.putMirrorSource` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `PutMirrorSourceOutput<S>` for this endpoint.*/
pub struct PutMirrorSourceResponse;
impl jacquard_common::xrpc::XrpcResp for PutMirrorSourceResponse {
    const NSID: &'static str = "app.rocksky.mirror.putMirrorSource";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = PutMirrorSourceOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for PutMirrorSource<S> {
    const NSID: &'static str = "app.rocksky.mirror.putMirrorSource";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Response = PutMirrorSourceResponse;
}

/** Endpoint marker for the `app.rocksky.mirror.putMirrorSource` procedure.

Path: `/xrpc/app.rocksky.mirror.putMirrorSource`. The request payload type is `PutMirrorSource<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct PutMirrorSourceRequest;
impl jacquard_common::xrpc::XrpcEndpoint for PutMirrorSourceRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.mirror.putMirrorSource";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Request<S: BosStr> = PutMirrorSource<S>;
    type Response = PutMirrorSourceResponse;
}
