//! Generating the actix surface from the lexicons.
//!
//! # What is generated, and what is not
//!
//! A handler's *body* is where every interesting decision lives — which tables
//! to read, how to rank, what to cache, what to answer when a row is missing.
//! None of that is in the lexicon, so none of it can be generated, and a
//! generated skeleton full of `todo!()` would be worse than nothing: it would
//! have to be edited, which makes it no longer generated.
//!
//! What *is* mechanical is the wiring, and getting it wrong is easy and quiet:
//!
//! - the route path must be exactly `/xrpc/<nsid>`
//! - a `query` must be `GET` and a `procedure` `POST`
//! - parameters must be deserialized from the query string, input from JSON
//! - the response must be the lexicon's output type, not something close to it
//!
//! So this generates three things:
//!
//! 1. **A method table** — every NSID with its kind, so a test can assert that
//!    the server registers exactly the methods the lexicons declare, and no
//!    others. That is the check that catches a typo'd path or a method nobody
//!    remembered to register.
//! 2. **A trait per method**, whose signature is the lexicon's types, emitted
//!    into the method's own module by [`crate::emit`]. An implementation that
//!    takes the wrong parameters or answers the wrong output fails to compile.
//!
//! The result is that the wiring is generated and checkable while the
//! behaviour stays hand-written.

use crate::lexicon::*;
use anyhow::Result;
use std::fmt::Write as _;

/// One method the lexicons declare.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MethodEntry {
    pub nsid: String,
    pub kind: MethodKind,
    /// Whether the lexicon declares query-string parameters.
    pub has_parameters: bool,
    /// Whether it declares a JSON request body.
    pub has_input: bool,
    /// Whether it declares a JSON response body.
    pub has_output: bool,
    pub description: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MethodKind {
    Query,
    Procedure,
}

impl MethodKind {
    pub fn http_method(&self) -> &'static str {
        match self {
            // The one rule that must not be got wrong: a query is a GET and a
            // procedure a POST. A swapped pair produces 404s that look like a
            // missing handler.
            MethodKind::Query => "get",
            MethodKind::Procedure => "post",
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            MethodKind::Query => "query",
            MethodKind::Procedure => "procedure",
        }
    }
}

/// Collects every method from the parsed documents.
pub fn methods(documents: &[(std::path::PathBuf, Document)]) -> Vec<MethodEntry> {
    let mut entries: Vec<MethodEntry> = documents
        .iter()
        .filter_map(|(_, document)| {
            let def = document.defs.get("main")?;
            let (kind, method) = match def {
                Def::Query(method) => (MethodKind::Query, method),
                Def::Procedure(method) => (MethodKind::Procedure, method),
                _ => return None,
            };

            Some(MethodEntry {
                nsid: document.id.clone(),
                kind,
                has_parameters: method.parameters.is_some(),
                has_input: method
                    .input
                    .as_ref()
                    .is_some_and(|body| body.schema.is_some()),
                has_output: method
                    .output
                    .as_ref()
                    .is_some_and(|body| body.schema.is_some()),
                description: method.description.clone(),
            })
        })
        .collect();

    entries.sort_by(|a, b| a.nsid.cmp(&b.nsid));
    entries
}

/// Generates the method table.
pub fn method_table(entries: &[MethodEntry]) -> Result<String> {
    let mut out = String::new();

    writeln!(out, "//! Every method the lexicons declare.")?;
    writeln!(out, "//!")?;
    writeln!(
        out,
        "//! Generated by `rocksky-lexicon-codegen`. Do not edit."
    )?;
    writeln!(out, "//!")?;
    writeln!(
        out,
        "//! The point of this table is that it can be compared against what the"
    )?;
    writeln!(
        out,
        "//! server actually registers: a method here with no route is unimplemented,"
    )?;
    writeln!(
        out,
        "//! and a route with no entry here is not in any lexicon. Both are bugs that"
    )?;
    writeln!(
        out,
        "//! are otherwise invisible until a client calls them."
    )?;
    writeln!(out)?;

    writeln!(
        out,
        "/// A lexicon method: `query` (GET) or `procedure` (POST)."
    )?;
    writeln!(out, "#[derive(Debug, Clone, Copy, PartialEq, Eq)]")?;
    writeln!(out, "pub enum MethodKind {{")?;
    writeln!(out, "    Query,")?;
    writeln!(out, "    Procedure,")?;
    writeln!(out, "}}")?;
    writeln!(out)?;
    writeln!(out, "impl MethodKind {{")?;
    writeln!(out, "    /// The HTTP method this kind is served over.")?;
    writeln!(out, "    pub fn http_method(&self) -> &'static str {{")?;
    writeln!(out, "        match self {{")?;
    writeln!(out, "            Self::Query => \"GET\",")?;
    writeln!(out, "            Self::Procedure => \"POST\",")?;
    writeln!(out, "        }}")?;
    writeln!(out, "    }}")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    writeln!(out, "/// One declared method.")?;
    writeln!(out, "#[derive(Debug, Clone, Copy, PartialEq, Eq)]")?;
    writeln!(out, "pub struct Method {{")?;
    writeln!(out, "    pub nsid: &'static str,")?;
    writeln!(out, "    pub kind: MethodKind,")?;
    writeln!(out, "    /// Whether it takes query-string parameters.")?;
    writeln!(out, "    pub has_parameters: bool,")?;
    writeln!(out, "    /// Whether it takes a JSON request body.")?;
    writeln!(out, "    pub has_input: bool,")?;
    writeln!(out, "    /// Whether it answers a JSON response body.")?;
    writeln!(out, "    pub has_output: bool,")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    writeln!(out, "impl Method {{")?;
    writeln!(out, "    /// The path this method is served at.")?;
    writeln!(out, "    pub fn path(&self) -> String {{")?;
    writeln!(out, "        format!(\"/xrpc/{{}}\", self.nsid)")?;
    writeln!(out, "    }}")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    writeln!(
        out,
        "/// Every method, sorted by NSID. {} of them.",
        entries.len()
    )?;
    writeln!(out, "pub const METHODS: &[Method] = &[")?;
    for entry in entries {
        if let Some(description) = &entry.description {
            writeln!(
                out,
                "    // {}",
                description.split_whitespace().collect::<Vec<_>>().join(" ")
            )?;
        }
        writeln!(out, "    Method {{")?;
        writeln!(out, "        nsid: \"{}\",", entry.nsid)?;
        writeln!(
            out,
            "        kind: MethodKind::{},",
            match entry.kind {
                MethodKind::Query => "Query",
                MethodKind::Procedure => "Procedure",
            }
        )?;
        writeln!(out, "        has_parameters: {},", entry.has_parameters)?;
        writeln!(out, "        has_input: {},", entry.has_input)?;
        writeln!(out, "        has_output: {},", entry.has_output)?;
        writeln!(out, "    }},")?;
    }
    writeln!(out, "];")?;
    writeln!(out)?;

    writeln!(out, "/// Looks a method up by NSID.")?;
    writeln!(out, "pub fn find(nsid: &str) -> Option<&'static Method> {{")?;
    writeln!(out, "    METHODS.iter().find(|method| method.nsid == nsid)")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    writeln!(out, "/// Every query's NSID.")?;
    writeln!(
        out,
        "pub fn queries() -> impl Iterator<Item = &'static str> {{"
    )?;
    writeln!(out, "    METHODS")?;
    writeln!(out, "        .iter()")?;
    writeln!(
        out,
        "        .filter(|method| method.kind == MethodKind::Query)"
    )?;
    writeln!(out, "        .map(|method| method.nsid)")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    writeln!(out, "/// Every procedure's NSID.")?;
    writeln!(
        out,
        "pub fn procedures() -> impl Iterator<Item = &'static str> {{"
    )?;
    writeln!(out, "    METHODS")?;
    writeln!(out, "        .iter()")?;
    writeln!(
        out,
        "        .filter(|method| method.kind == MethodKind::Procedure)"
    )?;
    writeln!(out, "        .map(|method| method.nsid)")?;
    writeln!(out, "}}")?;

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn document(raw: serde_json::Value) -> (std::path::PathBuf, Document) {
        (
            std::path::PathBuf::from("test.json"),
            serde_json::from_value(raw).expect("parses"),
        )
    }

    fn query(nsid: &str) -> (std::path::PathBuf, Document) {
        document(serde_json::json!({
            "lexicon": 1,
            "id": nsid,
            "defs": {
                "main": {
                    "type": "query",
                    "description": "Get the things",
                    "parameters": {
                        "type": "params",
                        "properties": { "limit": { "type": "integer" } }
                    },
                    "output": {
                        "encoding": "application/json",
                        "schema": { "type": "object", "properties": {} }
                    }
                }
            }
        }))
    }

    fn procedure(nsid: &str) -> (std::path::PathBuf, Document) {
        document(serde_json::json!({
            "lexicon": 1,
            "id": nsid,
            "defs": {
                "main": {
                    "type": "procedure",
                    "input": {
                        "encoding": "application/json",
                        "schema": { "type": "object", "properties": {} }
                    },
                    "output": {
                        "encoding": "application/json",
                        "schema": { "type": "object", "properties": {} }
                    }
                }
            }
        }))
    }

    #[test]
    fn queries_and_procedures_are_collected() {
        let documents = vec![
            query("app.rocksky.song.getSongs"),
            procedure("app.rocksky.song.createSong"),
            // A defs document declares no method.
            document(serde_json::json!({
                "lexicon": 1,
                "id": "app.rocksky.song.defs",
                "defs": { "songView": { "type": "object", "properties": {} } }
            })),
        ];

        let entries = methods(&documents);
        assert_eq!(entries.len(), 2, "only the methods: {entries:?}");

        // Sorted by NSID, so the table is stable across runs.
        assert_eq!(entries[0].nsid, "app.rocksky.song.createSong");
        assert_eq!(entries[0].kind, MethodKind::Procedure);
        assert!(entries[0].has_input);
        assert!(!entries[0].has_parameters);

        assert_eq!(entries[1].nsid, "app.rocksky.song.getSongs");
        assert_eq!(entries[1].kind, MethodKind::Query);
        assert!(entries[1].has_parameters);
        assert!(!entries[1].has_input);
    }

    /// The rule that must not break: a query is a GET, a procedure a POST.
    #[test]
    fn a_query_is_a_get_and_a_procedure_a_post() {
        assert_eq!(MethodKind::Query.http_method(), "get");
        assert_eq!(MethodKind::Procedure.http_method(), "post");
    }

    #[test]
    fn a_record_document_contributes_no_method() {
        let documents = vec![document(serde_json::json!({
            "lexicon": 1,
            "id": "app.rocksky.scrobble",
            "defs": {
                "main": {
                    "type": "record",
                    "record": { "type": "object", "properties": {} }
                }
            }
        }))];

        assert!(methods(&documents).is_empty());
    }

    #[test]
    fn the_table_carries_every_method_and_its_shape() {
        let entries = methods(&vec![
            query("app.rocksky.song.getSongs"),
            procedure("app.rocksky.song.createSong"),
        ]);
        let source = method_table(&entries).unwrap();

        assert!(
            source.contains("pub const METHODS: &[Method] = &["),
            "{source}"
        );
        assert!(
            source.contains("nsid: \"app.rocksky.song.getSongs\","),
            "{source}"
        );
        assert!(source.contains("kind: MethodKind::Query,"), "{source}");
        assert!(source.contains("kind: MethodKind::Procedure,"), "{source}");
        assert!(source.contains("has_parameters: true,"), "{source}");
        assert!(source.contains("has_input: true,"), "{source}");
        // The path is derived, so it cannot drift from the NSID.
        assert!(
            source.contains("format!(\"/xrpc/{}\", self.nsid)"),
            "{source}"
        );
    }
}
