import { RootStackParamList } from "@/src/Navigation";
import { NavigationProp, useNavigation } from "@react-navigation/native";
import { Linking } from "react-native";
import AlbumDetails from "./AlbumDetails";

const album = {
  id: "1",
  title: "Meteora 20th Anniversary Edition",
  artist: "Linkin Park",
  albumArt: "https://i.scdn.co/image/ab67616d0000b273aeb14ead136118a987246b63",
  artistUri: "",
  uri: "",
  year: 2023,
  releaseDate: "2023-04-07T00:00:00.000Z",
  label: "℗ 2023 Warner Records Inc.",
  tracks: [
    {
      id: "1",
      title: "Foreword",
      artist: "Linkin Park",
      artistUri: "",
      trackNumber: 1,
      discNumber: 1,
      uri: "",
    },
    {
      id: "2",
      title: "Don't Stay",
      artist: "Linkin Park",
      artistUri: "",
      trackNumber: 2,
      discNumber: 1,
      uri: "",
    },
    {
      id: "3",
      title: "Somewhere I Belong",
      artist: "Linkin Park",
      artistUri: "",
      trackNumber: 3,
      discNumber: 1,
      uri: "",
    },
    {
      id: "4",
      title: "Lying from You",
      artist: "Linkin Park",
      artistUri: "",
      trackNumber: 4,
      discNumber: 1,
      uri: "",
    },
    {
      id: "5",
      title: "Hit the Floor",
      artist: "Linkin Park",
      artistUri: "",
      trackNumber: 5,
      discNumber: 1,
      uri: "",
    },
    {
      id: "6",
      title: "Easier to Run",
      artist: "Linkin Park",
      artistUri: "",
      trackNumber: 6,
      discNumber: 1,
      uri: "",
    },
    {
      id: "7",
      title: "Faint",
      artist: "Linkin Park",
      artistUri: "",
      trackNumber: 7,
      discNumber: 1,
      uri: "",
    },
    {
      id: "8",
      title: "Figure.09",
      artist: "Linkin Park",
      artistUri: "",
      trackNumber: 8,
      discNumber: 1,
      uri: "",
    },
    {
      id: "9",
      title: "Breaking the Habit",
      artist: "Linkin Park",
      artistUri: "",
      trackNumber: 9,
      discNumber: 1,
      uri: "",
    },
    {
      id: "10",
      title: "From the Inside",
      artist: "Linkin Park",
      artistUri: "",
      trackNumber: 10,
      discNumber: 1,
      uri: "",
    },
    {
      id: "11",
      title: "Nobody's Listening",
      artist: "Linkin Park",
      artistUri: "",
      trackNumber: 11,
      discNumber: 1,
      uri: "",
    },
    {
      id: "12",
      title: "Session",
      artist: "Linkin Park",
      artistUri: "",
      trackNumber: 12,
      discNumber: 1,
      uri: "",
    },
    {
      id: "13",
      title: "Numb",
      artist: "Linkin Park",
      artistUri: "",
      trackNumber: 13,
      discNumber: 1,
      uri: "",
    },
    {
      id: "14",
      title: "Don't Stay (Live in Texas)",
      artist: "Linkin Park",
      artistUri: "",
      trackNumber: 1,
      discNumber: 2,
      uri: "",
    },
    {
      id: "15",
      title: "Somewhere I Belong (Live in Texas)",
      artist: "Linkin Park",
      artistUri: "",
      trackNumber: 2,
      discNumber: 2,
      uri: "",
    },
    {
      id: "16",
      title: "Lying from You (Live in Texas)",
      artist: "Linkin Park",
      artistUri: "",
      trackNumber: 3,
      discNumber: 2,
      uri: "",
    },
    {
      id: "17",
      title: "Papercut (Live in Texas)",
      artist: "Linkin Park",
      artistUri: "",
      trackNumber: 4,
      discNumber: 2,
      uri: "",
    },
    {
      id: "18",
      title: "Points of Authority (Live in Texas)",
      artist: "Linkin Park",
      artistUri: "",
      trackNumber: 5,
      discNumber: 2,
      uri: "",
    },
    {
      id: "19",
      title: "Runaway (Live in Texas)",
      artist: "Linkin Park",
      artistUri: "",
      trackNumber: 6,
      discNumber: 2,
      uri: "",
    },
    {
      id: "20",
      title: "Faint (Live in Texas)",
      artist: "Linkin Park",
      artistUri: "",
      trackNumber: 7,
      discNumber: 2,
      uri: "",
    },
    {
      id: "21",
      title: "From the Inside (Live in Texas)",
      artist: "Linkin Park",
      artistUri: "",
      trackNumber: 8,
      discNumber: 2,
      uri: "",
    },
    {
      id: "22",
      title: "Figure.09 (Live in Texas)",
      artist: "Linkin Park",
      artistUri: "",
      trackNumber: 9,
      discNumber: 2,
      uri: "",
    },
  ],
};

const AlbumDetailsWithData = () => {
  const navigation = useNavigation<NavigationProp<RootStackParamList>>();
  return (
    <AlbumDetails
      {...album}
      onPressArtist={() => navigation.navigate("ArtistDetails")}
      onPressTrack={() => navigation.navigate("SongDetails")}
      onViewOnPDSls={(did: string) => Linking.openURL(`https://pdsls.dev`)}
    />
  );
};

export default AlbumDetailsWithData;
