// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.stats.getStats
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::app_rocksky::stats::StatsView;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::ident::AtIdentifier;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetStats<S: BosStr = DefaultStr> {
    pub did: AtIdentifier<S>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetStatsOutput<S: BosStr = DefaultStr> {
    #[serde(flatten)]
    pub value: StatsView<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.rocksky.stats.getStats` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetStatsOutput<S>` for this endpoint.*/
pub struct GetStatsResponse;
impl jacquard_common::xrpc::XrpcResp for GetStatsResponse {
    const NSID: &'static str = "app.rocksky.stats.getStats";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetStatsOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetStats<S> {
    const NSID: &'static str = "app.rocksky.stats.getStats";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetStatsResponse;
}

/** Endpoint marker for the `app.rocksky.stats.getStats` query.

Path: `/xrpc/app.rocksky.stats.getStats`. The request payload type is `GetStats<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetStatsRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetStatsRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.stats.getStats";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetStats<S>;
    type Response = GetStatsResponse;
}

pub mod get_stats_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Did;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Did = Unset;
    }
    ///State transition - sets the `did` field to Set
    pub struct SetDid<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetDid<St> {}
    impl<St: State> State for SetDid<St> {
        type Did = Set<members::did>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `did` field
        pub struct did(());
    }
}

/// Builder for constructing an instance of this type.
pub struct GetStatsBuilder<St: get_stats_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<AtIdentifier<S>>,),
    _type: PhantomData<fn() -> S>,
}

impl GetStats<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GetStatsBuilder<get_stats_state::Empty, DefaultStr> {
        GetStatsBuilder::new()
    }
}

impl<S: BosStr> GetStats<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetStatsBuilder<get_stats_state::Empty, S> {
        GetStatsBuilder::builder()
    }
}

impl GetStatsBuilder<get_stats_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetStatsBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GetStatsBuilder<get_stats_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetStatsBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetStatsBuilder<St, S>
where
    St: get_stats_state::State,
    St::Did: get_stats_state::IsUnset,
{
    /// Set the `did` field (required)
    pub fn did(
        mut self,
        value: impl Into<AtIdentifier<S>>,
    ) -> GetStatsBuilder<get_stats_state::SetDid<St>, S> {
        self._fields.0 = Option::Some(value.into());
        GetStatsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetStatsBuilder<St, S>
where
    St: get_stats_state::State,
    St::Did: get_stats_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> GetStats<S> {
        GetStats {
            did: self._fields.0.unwrap(),
        }
    }
}
