// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.dropbox.downloadFile
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::bytes::Bytes;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct DownloadFile<S: BosStr = DefaultStr> {
    pub file_id: S,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct DownloadFileOutput {
    pub body: Bytes,
}

/** Response marker for the `app.rocksky.dropbox.downloadFile` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `DownloadFileOutput` for this endpoint.*/
pub struct DownloadFileResponse;
impl jacquard_common::xrpc::XrpcResp for DownloadFileResponse {
    const NSID: &'static str = "app.rocksky.dropbox.downloadFile";
    const ENCODING: &'static str = "application/octet-stream";
    type Output<S: BosStr> = DownloadFileOutput;
    type Err = jacquard_common::xrpc::GenericError;
    fn encode_output<S: BosStr>(
        output: &Self::Output<S>,
    ) -> Result<Vec<u8>, jacquard_common::xrpc::EncodeError>
    where
        Self::Output<S>: Serialize,
    {
        Ok(output.body.to_vec())
    }
    fn decode_output<'de, S>(
        body: &'de [u8],
    ) -> Result<Self::Output<S>, jacquard_common::error::DecodeError>
    where
        S: BosStr + Deserialize<'de>,
        Self::Output<S>: Deserialize<'de>,
    {
        Ok(DownloadFileOutput {
            body: jacquard_common::deps::bytes::Bytes::copy_from_slice(body),
        })
    }
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for DownloadFile<S> {
    const NSID: &'static str = "app.rocksky.dropbox.downloadFile";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = DownloadFileResponse;
}

/** Endpoint marker for the `app.rocksky.dropbox.downloadFile` query.

Path: `/xrpc/app.rocksky.dropbox.downloadFile`. The request payload type is `DownloadFile<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct DownloadFileRequest;
impl jacquard_common::xrpc::XrpcEndpoint for DownloadFileRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.dropbox.downloadFile";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = DownloadFile<S>;
    type Response = DownloadFileResponse;
}

pub mod download_file_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type FileId;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type FileId = Unset;
    }
    ///State transition - sets the `file_id` field to Set
    pub struct SetFileId<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetFileId<St> {}
    impl<St: State> State for SetFileId<St> {
        type FileId = Set<members::file_id>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `file_id` field
        pub struct file_id(());
    }
}

/// Builder for constructing an instance of this type.
pub struct DownloadFileBuilder<St: download_file_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>,),
    _type: PhantomData<fn() -> S>,
}

impl DownloadFile<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> DownloadFileBuilder<download_file_state::Empty, DefaultStr> {
        DownloadFileBuilder::new()
    }
}

impl<S: BosStr> DownloadFile<S> {
    /// Create a new builder for this type
    pub fn builder() -> DownloadFileBuilder<download_file_state::Empty, S> {
        DownloadFileBuilder::builder()
    }
}

impl DownloadFileBuilder<download_file_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        DownloadFileBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> DownloadFileBuilder<download_file_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        DownloadFileBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> DownloadFileBuilder<St, S>
where
    St: download_file_state::State,
    St::FileId: download_file_state::IsUnset,
{
    /// Set the `fileId` field (required)
    pub fn file_id(
        mut self,
        value: impl Into<S>,
    ) -> DownloadFileBuilder<download_file_state::SetFileId<St>, S> {
        self._fields.0 = Option::Some(value.into());
        DownloadFileBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> DownloadFileBuilder<St, S>
where
    St: download_file_state::State,
    St::FileId: download_file_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> DownloadFile<S> {
        DownloadFile {
            file_id: self._fields.0.unwrap(),
        }
    }
}
