// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.dropbox.getMetadata
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::app_rocksky::dropbox::FileView;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetMetadata<S: BosStr = DefaultStr> {
    pub path: S,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetMetadataOutput<S: BosStr = DefaultStr> {
    #[serde(flatten)]
    pub value: FileView<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.rocksky.dropbox.getMetadata` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetMetadataOutput<S>` for this endpoint.*/
pub struct GetMetadataResponse;
impl jacquard_common::xrpc::XrpcResp for GetMetadataResponse {
    const NSID: &'static str = "app.rocksky.dropbox.getMetadata";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetMetadataOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetMetadata<S> {
    const NSID: &'static str = "app.rocksky.dropbox.getMetadata";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetMetadataResponse;
}

/** Endpoint marker for the `app.rocksky.dropbox.getMetadata` query.

Path: `/xrpc/app.rocksky.dropbox.getMetadata`. The request payload type is `GetMetadata<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetMetadataRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetMetadataRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.dropbox.getMetadata";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetMetadata<S>;
    type Response = GetMetadataResponse;
}

pub mod get_metadata_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Path;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Path = Unset;
    }
    ///State transition - sets the `path` field to Set
    pub struct SetPath<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetPath<St> {}
    impl<St: State> State for SetPath<St> {
        type Path = Set<members::path>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `path` field
        pub struct path(());
    }
}

/// Builder for constructing an instance of this type.
pub struct GetMetadataBuilder<St: get_metadata_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>,),
    _type: PhantomData<fn() -> S>,
}

impl GetMetadata<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GetMetadataBuilder<get_metadata_state::Empty, DefaultStr> {
        GetMetadataBuilder::new()
    }
}

impl<S: BosStr> GetMetadata<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetMetadataBuilder<get_metadata_state::Empty, S> {
        GetMetadataBuilder::builder()
    }
}

impl GetMetadataBuilder<get_metadata_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetMetadataBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GetMetadataBuilder<get_metadata_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetMetadataBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetMetadataBuilder<St, S>
where
    St: get_metadata_state::State,
    St::Path: get_metadata_state::IsUnset,
{
    /// Set the `path` field (required)
    pub fn path(
        mut self,
        value: impl Into<S>,
    ) -> GetMetadataBuilder<get_metadata_state::SetPath<St>, S> {
        self._fields.0 = Option::Some(value.into());
        GetMetadataBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetMetadataBuilder<St, S>
where
    St: get_metadata_state::State,
    St::Path: get_metadata_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> GetMetadata<S> {
        GetMetadata {
            path: self._fields.0.unwrap(),
        }
    }
}
