// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.feed.describeFeedGenerator
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::app_rocksky::feed::FeedUriView;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::ident::AtIdentifier;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct DescribeFeedGenerator;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct DescribeFeedGeneratorOutput<S: BosStr = DefaultStr> {
    ///The DID of the feed generator.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub did: Option<AtIdentifier<S>>,
    ///List of feed URIs generated by this feed generator.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub feeds: Option<Vec<FeedUriView<S>>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.rocksky.feed.describeFeedGenerator` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `DescribeFeedGeneratorOutput<S>` for this endpoint.*/
pub struct DescribeFeedGeneratorResponse;
impl jacquard_common::xrpc::XrpcResp for DescribeFeedGeneratorResponse {
    const NSID: &'static str = "app.rocksky.feed.describeFeedGenerator";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = DescribeFeedGeneratorOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl jacquard_common::xrpc::XrpcRequest for DescribeFeedGenerator {
    const NSID: &'static str = "app.rocksky.feed.describeFeedGenerator";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = DescribeFeedGeneratorResponse;
}

/** Endpoint marker for the `app.rocksky.feed.describeFeedGenerator` query.

Path: `/xrpc/app.rocksky.feed.describeFeedGenerator`. The request payload type is `DescribeFeedGenerator`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct DescribeFeedGeneratorRequest;
impl jacquard_common::xrpc::XrpcEndpoint for DescribeFeedGeneratorRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.feed.describeFeedGenerator";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = DescribeFeedGenerator;
    type Response = DescribeFeedGeneratorResponse;
}
