// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.feed.getFeedGenerators
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::app_rocksky::feed::FeedGeneratorsView;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct GetFeedGenerators {
    /// (min: 1)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetFeedGeneratorsOutput<S: BosStr = DefaultStr> {
    #[serde(flatten)]
    pub value: FeedGeneratorsView<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.rocksky.feed.getFeedGenerators` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetFeedGeneratorsOutput<S>` for this endpoint.*/
pub struct GetFeedGeneratorsResponse;
impl jacquard_common::xrpc::XrpcResp for GetFeedGeneratorsResponse {
    const NSID: &'static str = "app.rocksky.feed.getFeedGenerators";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetFeedGeneratorsOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl jacquard_common::xrpc::XrpcRequest for GetFeedGenerators {
    const NSID: &'static str = "app.rocksky.feed.getFeedGenerators";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetFeedGeneratorsResponse;
}

/** Endpoint marker for the `app.rocksky.feed.getFeedGenerators` query.

Path: `/xrpc/app.rocksky.feed.getFeedGenerators`. The request payload type is `GetFeedGenerators`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetFeedGeneratorsRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetFeedGeneratorsRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.feed.getFeedGenerators";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetFeedGenerators;
    type Response = GetFeedGeneratorsResponse;
}

pub mod get_feed_generators_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type.
pub struct GetFeedGeneratorsBuilder<St: get_feed_generators_state::State> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<i64>,),
}

impl GetFeedGenerators {
    /// Create a new builder for this type.
    pub fn new() -> GetFeedGeneratorsBuilder<get_feed_generators_state::Empty> {
        GetFeedGeneratorsBuilder::new()
    }
}

impl GetFeedGeneratorsBuilder<get_feed_generators_state::Empty> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetFeedGeneratorsBuilder {
            _state: PhantomData,
            _fields: (None,),
        }
    }
}

impl GetFeedGeneratorsBuilder<get_feed_generators_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetFeedGeneratorsBuilder {
            _state: PhantomData,
            _fields: (None,),
        }
    }
}

impl<St: get_feed_generators_state::State> GetFeedGeneratorsBuilder<St> {
    /// Set the `size` field (optional)
    pub fn size(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `size` field to an Option value (optional)
    pub fn maybe_size(mut self, value: Option<i64>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St> GetFeedGeneratorsBuilder<St>
where
    St: get_feed_generators_state::State,
{
    /// Build the final struct.
    pub fn build(self) -> GetFeedGenerators {
        GetFeedGenerators {
            size: self._fields.0,
        }
    }
}
