// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.feed.getStories
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::app_rocksky::feed::StoriesView;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::AtUri;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetStories<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub feed: Option<AtUri<S>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub following: Option<bool>,
    /// (min: 1)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetStoriesOutput<S: BosStr = DefaultStr> {
    #[serde(flatten)]
    pub value: StoriesView<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.rocksky.feed.getStories` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetStoriesOutput<S>` for this endpoint.*/
pub struct GetStoriesResponse;
impl jacquard_common::xrpc::XrpcResp for GetStoriesResponse {
    const NSID: &'static str = "app.rocksky.feed.getStories";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetStoriesOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetStories<S> {
    const NSID: &'static str = "app.rocksky.feed.getStories";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetStoriesResponse;
}

/** Endpoint marker for the `app.rocksky.feed.getStories` query.

Path: `/xrpc/app.rocksky.feed.getStories`. The request payload type is `GetStories<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetStoriesRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetStoriesRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.feed.getStories";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetStories<S>;
    type Response = GetStoriesResponse;
}

pub mod get_stories_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type.
pub struct GetStoriesBuilder<St: get_stories_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<AtUri<S>>, Option<bool>, Option<i64>),
    _type: PhantomData<fn() -> S>,
}

impl GetStories<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GetStoriesBuilder<get_stories_state::Empty, DefaultStr> {
        GetStoriesBuilder::new()
    }
}

impl<S: BosStr> GetStories<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetStoriesBuilder<get_stories_state::Empty, S> {
        GetStoriesBuilder::builder()
    }
}

impl GetStoriesBuilder<get_stories_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetStoriesBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GetStoriesBuilder<get_stories_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetStoriesBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: get_stories_state::State, S: BosStr> GetStoriesBuilder<St, S> {
    /// Set the `feed` field (optional)
    pub fn feed(mut self, value: impl Into<Option<AtUri<S>>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `feed` field to an Option value (optional)
    pub fn maybe_feed(mut self, value: Option<AtUri<S>>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St: get_stories_state::State, S: BosStr> GetStoriesBuilder<St, S> {
    /// Set the `following` field (optional)
    pub fn following(mut self, value: impl Into<Option<bool>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `following` field to an Option value (optional)
    pub fn maybe_following(mut self, value: Option<bool>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St: get_stories_state::State, S: BosStr> GetStoriesBuilder<St, S> {
    /// Set the `size` field (optional)
    pub fn size(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `size` field to an Option value (optional)
    pub fn maybe_size(mut self, value: Option<i64>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St, S: BosStr> GetStoriesBuilder<St, S>
where
    St: get_stories_state::State,
{
    /// Build the final struct.
    pub fn build(self) -> GetStories<S> {
        GetStories {
            feed: self._fields.0,
            following: self._fields.1,
            size: self._fields.2,
        }
    }
}
