// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.feed.getAlbumRecommendations
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::app_rocksky::feed::RecommendedAlbumsView;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetAlbumRecommendations<S: BosStr = DefaultStr> {
    pub did: S,
    /// (min: 1, max: 100)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetAlbumRecommendationsOutput<S: BosStr = DefaultStr> {
    #[serde(flatten)]
    pub value: RecommendedAlbumsView<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.rocksky.feed.getAlbumRecommendations` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetAlbumRecommendationsOutput<S>` for this endpoint.*/
pub struct GetAlbumRecommendationsResponse;
impl jacquard_common::xrpc::XrpcResp for GetAlbumRecommendationsResponse {
    const NSID: &'static str = "app.rocksky.feed.getAlbumRecommendations";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetAlbumRecommendationsOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetAlbumRecommendations<S> {
    const NSID: &'static str = "app.rocksky.feed.getAlbumRecommendations";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetAlbumRecommendationsResponse;
}

/** Endpoint marker for the `app.rocksky.feed.getAlbumRecommendations` query.

Path: `/xrpc/app.rocksky.feed.getAlbumRecommendations`. The request payload type is `GetAlbumRecommendations<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetAlbumRecommendationsRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetAlbumRecommendationsRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.feed.getAlbumRecommendations";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetAlbumRecommendations<S>;
    type Response = GetAlbumRecommendationsResponse;
}

pub mod get_album_recommendations_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Did;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Did = Unset;
    }
    ///State transition - sets the `did` field to Set
    pub struct SetDid<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetDid<St> {}
    impl<St: State> State for SetDid<St> {
        type Did = Set<members::did>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `did` field
        pub struct did(());
    }
}

/// Builder for constructing an instance of this type.
pub struct GetAlbumRecommendationsBuilder<
    St: get_album_recommendations_state::State,
    S: BosStr = DefaultStr,
> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>, Option<i64>),
    _type: PhantomData<fn() -> S>,
}

impl GetAlbumRecommendations<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new(
    ) -> GetAlbumRecommendationsBuilder<get_album_recommendations_state::Empty, DefaultStr> {
        GetAlbumRecommendationsBuilder::new()
    }
}

impl<S: BosStr> GetAlbumRecommendations<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetAlbumRecommendationsBuilder<get_album_recommendations_state::Empty, S> {
        GetAlbumRecommendationsBuilder::builder()
    }
}

impl GetAlbumRecommendationsBuilder<get_album_recommendations_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetAlbumRecommendationsBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GetAlbumRecommendationsBuilder<get_album_recommendations_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetAlbumRecommendationsBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetAlbumRecommendationsBuilder<St, S>
where
    St: get_album_recommendations_state::State,
    St::Did: get_album_recommendations_state::IsUnset,
{
    /// Set the `did` field (required)
    pub fn did(
        mut self,
        value: impl Into<S>,
    ) -> GetAlbumRecommendationsBuilder<get_album_recommendations_state::SetDid<St>, S> {
        self._fields.0 = Option::Some(value.into());
        GetAlbumRecommendationsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: get_album_recommendations_state::State, S: BosStr> GetAlbumRecommendationsBuilder<St, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St, S: BosStr> GetAlbumRecommendationsBuilder<St, S>
where
    St: get_album_recommendations_state::State,
    St::Did: get_album_recommendations_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> GetAlbumRecommendations<S> {
        GetAlbumRecommendations {
            did: self._fields.0.unwrap(),
            limit: self._fields.1,
        }
    }
}
