// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.feed.getFeed
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::app_rocksky::feed::FeedView;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::AtUri;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetFeed<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    pub feed: AtUri<S>,
    /// (min: 1)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetFeedOutput<S: BosStr = DefaultStr> {
    #[serde(flatten)]
    pub value: FeedView<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.rocksky.feed.getFeed` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetFeedOutput<S>` for this endpoint.*/
pub struct GetFeedResponse;
impl jacquard_common::xrpc::XrpcResp for GetFeedResponse {
    const NSID: &'static str = "app.rocksky.feed.getFeed";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetFeedOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetFeed<S> {
    const NSID: &'static str = "app.rocksky.feed.getFeed";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetFeedResponse;
}

/** Endpoint marker for the `app.rocksky.feed.getFeed` query.

Path: `/xrpc/app.rocksky.feed.getFeed`. The request payload type is `GetFeed<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetFeedRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetFeedRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.feed.getFeed";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetFeed<S>;
    type Response = GetFeedResponse;
}

pub mod get_feed_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Feed;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Feed = Unset;
    }
    ///State transition - sets the `feed` field to Set
    pub struct SetFeed<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetFeed<St> {}
    impl<St: State> State for SetFeed<St> {
        type Feed = Set<members::feed>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `feed` field
        pub struct feed(());
    }
}

/// Builder for constructing an instance of this type.
pub struct GetFeedBuilder<St: get_feed_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>, Option<AtUri<S>>, Option<i64>),
    _type: PhantomData<fn() -> S>,
}

impl GetFeed<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GetFeedBuilder<get_feed_state::Empty, DefaultStr> {
        GetFeedBuilder::new()
    }
}

impl<S: BosStr> GetFeed<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetFeedBuilder<get_feed_state::Empty, S> {
        GetFeedBuilder::builder()
    }
}

impl GetFeedBuilder<get_feed_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetFeedBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GetFeedBuilder<get_feed_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetFeedBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: get_feed_state::State, S: BosStr> GetFeedBuilder<St, S> {
    /// Set the `cursor` field (optional)
    pub fn cursor(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `cursor` field to an Option value (optional)
    pub fn maybe_cursor(mut self, value: Option<S>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St, S: BosStr> GetFeedBuilder<St, S>
where
    St: get_feed_state::State,
    St::Feed: get_feed_state::IsUnset,
{
    /// Set the `feed` field (required)
    pub fn feed(
        mut self,
        value: impl Into<AtUri<S>>,
    ) -> GetFeedBuilder<get_feed_state::SetFeed<St>, S> {
        self._fields.1 = Option::Some(value.into());
        GetFeedBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: get_feed_state::State, S: BosStr> GetFeedBuilder<St, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St, S: BosStr> GetFeedBuilder<St, S>
where
    St: get_feed_state::State,
    St::Feed: get_feed_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> GetFeed<S> {
        GetFeed {
            cursor: self._fields.0,
            feed: self._fields.1.unwrap(),
            limit: self._fields.2,
        }
    }
}
