export const categories = [
  "all",
  "following",
  "afrobeat",
  "afrobeats",
  "alternative metal",
  "anime",
  "art pop",
  "breakcore",
  "chicago drill",
  "chillwave",
  "country hip hop",
  "crunk",
  "dance pop",
  "deep house",
  "drill",
  "dubstep",
  "emo",
  "grunge",
  "hard rock",
  "heavy metal",
  "hip hop",
  "house",
  "hyperpop",
  "indie",
  "indie rock",
  "j-pop",
  "j-rock",
  "jazz",
  "k-pop",
  "lo-fi",
  "metal",
  "metalcore",
  "midwest emo",
  "nu metal",
  "pop punk",
  "post-grunge",
  "rap",
  "rap metal",
  "r&b",
  "rock",
  "southern hip hop",
  "speedcore",
  "swedish pop",
  "synthwave",
  "thrash metal",
  "trap",
  "trap soul",
  "tropical house",
  "vaporwave",
  "visual kei",
  "vocaloid",
  "west coast hip hop",
].filter((category) =>
  localStorage.getItem("did") ? true : category !== "following",
);
