// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.spotify.getCurrentlyPlaying
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::app_rocksky::player::CurrentlyPlayingViewDetailed;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::ident::AtIdentifier;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetCurrentlyPlaying<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor: Option<AtIdentifier<S>>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetCurrentlyPlayingOutput<S: BosStr = DefaultStr> {
    #[serde(flatten)]
    pub value: CurrentlyPlayingViewDetailed<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.rocksky.spotify.getCurrentlyPlaying` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetCurrentlyPlayingOutput<S>` for this endpoint.*/
pub struct GetCurrentlyPlayingResponse;
impl jacquard_common::xrpc::XrpcResp for GetCurrentlyPlayingResponse {
    const NSID: &'static str = "app.rocksky.spotify.getCurrentlyPlaying";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetCurrentlyPlayingOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetCurrentlyPlaying<S> {
    const NSID: &'static str = "app.rocksky.spotify.getCurrentlyPlaying";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetCurrentlyPlayingResponse;
}

/** Endpoint marker for the `app.rocksky.spotify.getCurrentlyPlaying` query.

Path: `/xrpc/app.rocksky.spotify.getCurrentlyPlaying`. The request payload type is `GetCurrentlyPlaying<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetCurrentlyPlayingRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetCurrentlyPlayingRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.spotify.getCurrentlyPlaying";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetCurrentlyPlaying<S>;
    type Response = GetCurrentlyPlayingResponse;
}

pub mod get_currently_playing_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type.
pub struct GetCurrentlyPlayingBuilder<
    St: get_currently_playing_state::State,
    S: BosStr = DefaultStr,
> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<AtIdentifier<S>>,),
    _type: PhantomData<fn() -> S>,
}

impl GetCurrentlyPlaying<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GetCurrentlyPlayingBuilder<get_currently_playing_state::Empty, DefaultStr> {
        GetCurrentlyPlayingBuilder::new()
    }
}

impl<S: BosStr> GetCurrentlyPlaying<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetCurrentlyPlayingBuilder<get_currently_playing_state::Empty, S> {
        GetCurrentlyPlayingBuilder::builder()
    }
}

impl GetCurrentlyPlayingBuilder<get_currently_playing_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetCurrentlyPlayingBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GetCurrentlyPlayingBuilder<get_currently_playing_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetCurrentlyPlayingBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<St: get_currently_playing_state::State, S: BosStr> GetCurrentlyPlayingBuilder<St, S> {
    /// Set the `actor` field (optional)
    pub fn actor(mut self, value: impl Into<Option<AtIdentifier<S>>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `actor` field to an Option value (optional)
    pub fn maybe_actor(mut self, value: Option<AtIdentifier<S>>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St, S: BosStr> GetCurrentlyPlayingBuilder<St, S>
where
    St: get_currently_playing_state::State,
{
    /// Build the final struct.
    pub fn build(self) -> GetCurrentlyPlaying<S> {
        GetCurrentlyPlaying {
            actor: self._fields.0,
        }
    }
}
