// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.spotify.previous
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};
/** Request marker for the `app.rocksky.spotify.previous` procedure.

This endpoint has no request parameters or input body; send this marker with `jacquard::Client`.*/

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Copy)]
pub struct Previous;
/** Response marker for the `app.rocksky.spotify.previous` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `()` for this endpoint.*/
pub struct PreviousResponse;
impl jacquard_common::xrpc::XrpcResp for PreviousResponse {
    const NSID: &'static str = "app.rocksky.spotify.previous";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = ();
    type Err = jacquard_common::xrpc::GenericError;
}

impl jacquard_common::xrpc::XrpcRequest for Previous {
    const NSID: &'static str = "app.rocksky.spotify.previous";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Response = PreviousResponse;
}

/** Endpoint marker for the `app.rocksky.spotify.previous` procedure.

Path: `/xrpc/app.rocksky.spotify.previous`. The request payload type is `Previous`; use this marker with lower-level `XrpcEndpoint` APIs when you need endpoint metadata.*/
pub struct PreviousRequest;
impl jacquard_common::xrpc::XrpcEndpoint for PreviousRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.spotify.previous";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Request<S: BosStr> = Previous;
    type Response = PreviousResponse;
}
