when:
  - event: ["push", "manual"]
    branch: ["main"]

engine: 'nixery'

clone:
  skip: false
  depth: 1
  submodules: false

dependencies:
  nixpkgs:
    - nodejs
    - pkg-config
    - rustc
    - cargo
    - gcc
    - duckdb
  github:NixOS/nixpkgs/nixpkgs-unstable:
    - bun

steps:
  - name: build apps/api
    command: |
      cd apps/api
      bun install --frozen-lockfile
      bun run build

  #- name: cargo build -p rockskyd --release
  #  command: |
  #    cargo build -p rockskyd --release
