import type { Context } from "context";
import type { Server } from "lexicon";
import getActorAlbums from "./app/rocksky/actor/getActorAlbums";
import getActorArtists from "./app/rocksky/actor/getActorArtists";
import getActorLovedSongs from "./app/rocksky/actor/getActorLovedSongs";
import getActorPlaylists from "./app/rocksky/actor/getActorPlaylists";
import getActorScrobbles from "./app/rocksky/actor/getActorScrobbles";
import getActorSongs from "./app/rocksky/actor/getActorSongs";
import getProfile from "./app/rocksky/actor/getProfile";
import getAlbum from "./app/rocksky/album/getAlbum";
import getAlbums from "./app/rocksky/album/getAlbums";
import getAlbumTracks from "./app/rocksky/album/getAlbumTracks";
import createApikey from "./app/rocksky/apikey/createApikey";
import getApikeys from "./app/rocksky/apikey/getApikeys";
import removeApikey from "./app/rocksky/apikey/removeApikey";
import updateApikey from "./app/rocksky/apikey/updateApikey";
import getArtist from "./app/rocksky/artist/getArtist";
import getArtistAlbums from "./app/rocksky/artist/getArtistAlbums";
import getArtistListeners from "./app/rocksky/artist/getArtistListeners";
import getArtists from "./app/rocksky/artist/getArtists";
import getArtistTracks from "./app/rocksky/artist/getArtistTracks";
import getScrobblesChart from "./app/rocksky/charts/getScrobblesChart";
import downloadFileFromDropbox from "./app/rocksky/dropbox/downloadFile";
import getFilesFromDropbox from "./app/rocksky/dropbox/getFiles";
import getMetadataFromDropbox from "./app/rocksky/dropbox/getMetadata";
import getTemporaryLinkFromDropbox from "./app/rocksky/dropbox/getTemporaryLink";
import getNowPlayings from "./app/rocksky/feed/getNowPlayings";
import search from "./app/rocksky/feed/search";
import downloadFileFromGoogleDrive from "./app/rocksky/googledrive/downloadFile";
import getFileFromGoogleDrive from "./app/rocksky/googledrive/getFile";
import getFilesFromGoogleDrive from "./app/rocksky/googledrive/getFiles";
import dislikeShout from "./app/rocksky/like/dislikeShout";
import dislikeSong from "./app/rocksky/like/dislikeSong";
import likeShout from "./app/rocksky/like/likeShout";
import likeSong from "./app/rocksky/like/likeSong";
import addItemsToQueue from "./app/rocksky/player/addItemsToQueue";
import getCurrentlyPlaying from "./app/rocksky/player/getCurrentlyPlaying";
import getPlaybackQueue from "./app/rocksky/player/getPlaybackQueue";
import next from "./app/rocksky/player/next";
import pause from "./app/rocksky/player/pause";
import play from "./app/rocksky/player/play";
import playDirectory from "./app/rocksky/player/playDirectory";
import playFile from "./app/rocksky/player/playFile";
import previous from "./app/rocksky/player/previous";
import seek from "./app/rocksky/player/seek";
import createPlaylist from "./app/rocksky/playlist/createPlaylist";
import getPlaylist from "./app/rocksky/playlist/getPlaylist";
import getPlaylists from "./app/rocksky/playlist/getPlaylists";
import insertDirectory from "./app/rocksky/playlist/insertDirectory";
import insertFiles from "./app/rocksky/playlist/insertFiles";
import removePlaylist from "./app/rocksky/playlist/removePlaylist";
import startPlaylist from "./app/rocksky/playlist/startPlaylist";
import createScrobble from "./app/rocksky/scrobble/createScrobble";
import getScrobble from "./app/rocksky/scrobble/getScrobble";
import getScrobbles from "./app/rocksky/scrobble/getScrobbles";
import createShout from "./app/rocksky/shout/createShout";
import getAlbumShouts from "./app/rocksky/shout/getAlbumShouts";
import getArtistShouts from "./app/rocksky/shout/getArtistShouts";
import getProfileShouts from "./app/rocksky/shout/getProfileShouts";
import getShoutReplies from "./app/rocksky/shout/getShoutReplies";
import getTrackShouts from "./app/rocksky/shout/getTrackShouts";
import removeShout from "./app/rocksky/shout/removeShout";
import replyShout from "./app/rocksky/shout/replyShout";
import reportShout from "./app/rocksky/shout/reportShout";
import createSong from "./app/rocksky/song/createSong";
import getSong from "./app/rocksky/song/getSong";
import getSongs from "./app/rocksky/song/getSongs";
import spotifyGetCurrentlyPlaying from "./app/rocksky/spotify/getCurrentlyPlaying";
import spotifyNext from "./app/rocksky/spotify/next";
import spotifyPause from "./app/rocksky/spotify/pause";
import spotifyPlay from "./app/rocksky/spotify/play";
import spotifyPrevious from "./app/rocksky/spotify/previous";
import spotifySeek from "./app/rocksky/spotify/seek";
import getStats from "./app/rocksky/stats/getStats";

export default function (server: Server, ctx: Context) {
  // app.rocksky
  getActorAlbums(server, ctx);
  getActorArtists(server, ctx);
  getActorLovedSongs(server, ctx);
  getActorPlaylists(server, ctx);
  getActorScrobbles(server, ctx);
  getActorSongs(server, ctx);
  getProfile(server, ctx);
  getAlbum(server, ctx);
  getAlbums(server, ctx);
  getAlbumTracks(server, ctx);
  createApikey(server, ctx);
  getApikeys(server, ctx);
  removeApikey(server, ctx);
  updateApikey(server, ctx);
  getArtist(server, ctx);
  getArtistAlbums(server, ctx);
  getArtists(server, ctx);
  getArtistListeners(server, ctx);
  getArtistTracks(server, ctx);
  getScrobblesChart(server, ctx);
  downloadFileFromDropbox(server, ctx);
  getFilesFromDropbox(server, ctx);
  getMetadataFromDropbox(server, ctx);
  getTemporaryLinkFromDropbox(server, ctx);
  getNowPlayings(server, ctx);
  search(server, ctx);
  downloadFileFromGoogleDrive(server, ctx);
  getFilesFromGoogleDrive(server, ctx);
  getFileFromGoogleDrive(server, ctx);
  dislikeShout(server, ctx);
  dislikeSong(server, ctx);
  likeShout(server, ctx);
  likeSong(server, ctx);
  getCurrentlyPlaying(server, ctx);
  next(server, ctx);
  play(server, ctx);
  pause(server, ctx);
  previous(server, ctx);
  seek(server, ctx);
  getPlaylist(server, ctx);
  getPlaylists(server, ctx);
  createScrobble(server, ctx);
  getScrobble(server, ctx);
  getScrobbles(server, ctx);
  createShout(server, ctx);
  getAlbumShouts(server, ctx);
  getArtistShouts(server, ctx);
  getProfileShouts(server, ctx);
  getTrackShouts(server, ctx);
  getShoutReplies(server, ctx);
  removeShout(server, ctx);
  replyShout(server, ctx);
  reportShout(server, ctx);
  getSong(server, ctx);
  getSongs(server, ctx);
  spotifyGetCurrentlyPlaying(server, ctx);
  spotifyNext(server, ctx);
  spotifyPause(server, ctx);
  spotifyPrevious(server, ctx);
  spotifySeek(server, ctx);
  spotifyPlay(server, ctx);
  getStats(server, ctx);
  createSong(server, ctx);
  addItemsToQueue(server, ctx);
  getPlaybackQueue(server, ctx);
  playDirectory(server, ctx);
  playFile(server, ctx);
  createPlaylist(server, ctx);
  insertDirectory(server, ctx);
  insertFiles(server, ctx);
  removePlaylist(server, ctx);
  startPlaylist(server, ctx);

  return server;
}
