// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.shout.getTrackShouts
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::AtUri;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetTrackShouts<S: BosStr = DefaultStr> {
    pub uri: AtUri<S>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetTrackShoutsOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub shouts: Option<Vec<Data<S>>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.rocksky.shout.getTrackShouts` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetTrackShoutsOutput<S>` for this endpoint.*/
pub struct GetTrackShoutsResponse;
impl jacquard_common::xrpc::XrpcResp for GetTrackShoutsResponse {
    const NSID: &'static str = "app.rocksky.shout.getTrackShouts";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetTrackShoutsOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetTrackShouts<S> {
    const NSID: &'static str = "app.rocksky.shout.getTrackShouts";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetTrackShoutsResponse;
}

/** Endpoint marker for the `app.rocksky.shout.getTrackShouts` query.

Path: `/xrpc/app.rocksky.shout.getTrackShouts`. The request payload type is `GetTrackShouts<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetTrackShoutsRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetTrackShoutsRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.shout.getTrackShouts";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetTrackShouts<S>;
    type Response = GetTrackShoutsResponse;
}

pub mod get_track_shouts_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Uri;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Uri = Unset;
    }
    ///State transition - sets the `uri` field to Set
    pub struct SetUri<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetUri<St> {}
    impl<St: State> State for SetUri<St> {
        type Uri = Set<members::uri>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `uri` field
        pub struct uri(());
    }
}

/// Builder for constructing an instance of this type.
pub struct GetTrackShoutsBuilder<St: get_track_shouts_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<AtUri<S>>,),
    _type: PhantomData<fn() -> S>,
}

impl GetTrackShouts<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GetTrackShoutsBuilder<get_track_shouts_state::Empty, DefaultStr> {
        GetTrackShoutsBuilder::new()
    }
}

impl<S: BosStr> GetTrackShouts<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetTrackShoutsBuilder<get_track_shouts_state::Empty, S> {
        GetTrackShoutsBuilder::builder()
    }
}

impl GetTrackShoutsBuilder<get_track_shouts_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetTrackShoutsBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GetTrackShoutsBuilder<get_track_shouts_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetTrackShoutsBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetTrackShoutsBuilder<St, S>
where
    St: get_track_shouts_state::State,
    St::Uri: get_track_shouts_state::IsUnset,
{
    /// Set the `uri` field (required)
    pub fn uri(
        mut self,
        value: impl Into<AtUri<S>>,
    ) -> GetTrackShoutsBuilder<get_track_shouts_state::SetUri<St>, S> {
        self._fields.0 = Option::Some(value.into());
        GetTrackShoutsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetTrackShoutsBuilder<St, S>
where
    St: get_track_shouts_state::State,
    St::Uri: get_track_shouts_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> GetTrackShouts<S> {
        GetTrackShouts {
            uri: self._fields.0.unwrap(),
        }
    }
}
