// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.shout.reportShout
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::app_rocksky::shout::ShoutView;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct ReportShout<S: BosStr = DefaultStr> {
    ///The reason for reporting the shout
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<S>,
    ///The unique identifier of the shout to report
    pub shout_id: S,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct ReportShoutOutput<S: BosStr = DefaultStr> {
    #[serde(flatten)]
    pub value: ShoutView<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.rocksky.shout.reportShout` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `ReportShoutOutput<S>` for this endpoint.*/
pub struct ReportShoutResponse;
impl jacquard_common::xrpc::XrpcResp for ReportShoutResponse {
    const NSID: &'static str = "app.rocksky.shout.reportShout";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = ReportShoutOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for ReportShout<S> {
    const NSID: &'static str = "app.rocksky.shout.reportShout";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Response = ReportShoutResponse;
}

/** Endpoint marker for the `app.rocksky.shout.reportShout` procedure.

Path: `/xrpc/app.rocksky.shout.reportShout`. The request payload type is `ReportShout<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct ReportShoutRequest;
impl jacquard_common::xrpc::XrpcEndpoint for ReportShoutRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.shout.reportShout";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Request<S: BosStr> = ReportShout<S>;
    type Response = ReportShoutResponse;
}
