// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.player.getPlaybackQueue
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::app_rocksky::player::PlaybackQueueViewDetailed;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetPlaybackQueue<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub player_id: Option<S>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetPlaybackQueueOutput<S: BosStr = DefaultStr> {
    #[serde(flatten)]
    pub value: PlaybackQueueViewDetailed<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.rocksky.player.getPlaybackQueue` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetPlaybackQueueOutput<S>` for this endpoint.*/
pub struct GetPlaybackQueueResponse;
impl jacquard_common::xrpc::XrpcResp for GetPlaybackQueueResponse {
    const NSID: &'static str = "app.rocksky.player.getPlaybackQueue";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetPlaybackQueueOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetPlaybackQueue<S> {
    const NSID: &'static str = "app.rocksky.player.getPlaybackQueue";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetPlaybackQueueResponse;
}

/** Endpoint marker for the `app.rocksky.player.getPlaybackQueue` query.

Path: `/xrpc/app.rocksky.player.getPlaybackQueue`. The request payload type is `GetPlaybackQueue<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetPlaybackQueueRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetPlaybackQueueRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.player.getPlaybackQueue";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetPlaybackQueue<S>;
    type Response = GetPlaybackQueueResponse;
}

pub mod get_playback_queue_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type.
pub struct GetPlaybackQueueBuilder<St: get_playback_queue_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>,),
    _type: PhantomData<fn() -> S>,
}

impl GetPlaybackQueue<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GetPlaybackQueueBuilder<get_playback_queue_state::Empty, DefaultStr> {
        GetPlaybackQueueBuilder::new()
    }
}

impl<S: BosStr> GetPlaybackQueue<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetPlaybackQueueBuilder<get_playback_queue_state::Empty, S> {
        GetPlaybackQueueBuilder::builder()
    }
}

impl GetPlaybackQueueBuilder<get_playback_queue_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetPlaybackQueueBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GetPlaybackQueueBuilder<get_playback_queue_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetPlaybackQueueBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<St: get_playback_queue_state::State, S: BosStr> GetPlaybackQueueBuilder<St, S> {
    /// Set the `playerId` field (optional)
    pub fn player_id(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `playerId` field to an Option value (optional)
    pub fn maybe_player_id(mut self, value: Option<S>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St, S: BosStr> GetPlaybackQueueBuilder<St, S>
where
    St: get_playback_queue_state::State,
{
    /// Build the final struct.
    pub fn build(self) -> GetPlaybackQueue<S> {
        GetPlaybackQueue {
            player_id: self._fields.0,
        }
    }
}
