// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.player.playFile
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct PlayFileParams<S: BosStr = DefaultStr> {
    pub file_id: S,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub player_id: Option<S>,
}

/** Request marker for the `app.rocksky.player.playFile` procedure.

This endpoint has no request parameters or input body; send this marker with `jacquard::Client`.*/

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Copy)]
pub struct PlayFile;
/** Response marker for the `app.rocksky.player.playFile` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `()` for this endpoint.*/
pub struct PlayFileResponse;
impl jacquard_common::xrpc::XrpcResp for PlayFileResponse {
    const NSID: &'static str = "app.rocksky.player.playFile";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = ();
    type Err = jacquard_common::xrpc::GenericError;
}

impl jacquard_common::xrpc::XrpcRequest for PlayFile {
    const NSID: &'static str = "app.rocksky.player.playFile";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Response = PlayFileResponse;
}

/** Endpoint marker for the `app.rocksky.player.playFile` procedure.

Path: `/xrpc/app.rocksky.player.playFile`. The request payload type is `PlayFile`; use this marker with lower-level `XrpcEndpoint` APIs when you need endpoint metadata.*/
pub struct PlayFileRequest;
impl jacquard_common::xrpc::XrpcEndpoint for PlayFileRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.player.playFile";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Request<S: BosStr> = PlayFile;
    type Response = PlayFileResponse;
}

pub mod play_file_params_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type FileId;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type FileId = Unset;
    }
    ///State transition - sets the `file_id` field to Set
    pub struct SetFileId<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetFileId<St> {}
    impl<St: State> State for SetFileId<St> {
        type FileId = Set<members::file_id>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `file_id` field
        pub struct file_id(());
    }
}

/// Builder for constructing an instance of this type.
pub struct PlayFileParamsBuilder<St: play_file_params_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>, Option<S>),
    _type: PhantomData<fn() -> S>,
}

impl PlayFileParams<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> PlayFileParamsBuilder<play_file_params_state::Empty, DefaultStr> {
        PlayFileParamsBuilder::new()
    }
}

impl<S: BosStr> PlayFileParams<S> {
    /// Create a new builder for this type
    pub fn builder() -> PlayFileParamsBuilder<play_file_params_state::Empty, S> {
        PlayFileParamsBuilder::builder()
    }
}

impl PlayFileParamsBuilder<play_file_params_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        PlayFileParamsBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> PlayFileParamsBuilder<play_file_params_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        PlayFileParamsBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> PlayFileParamsBuilder<St, S>
where
    St: play_file_params_state::State,
    St::FileId: play_file_params_state::IsUnset,
{
    /// Set the `fileId` field (required)
    pub fn file_id(
        mut self,
        value: impl Into<S>,
    ) -> PlayFileParamsBuilder<play_file_params_state::SetFileId<St>, S> {
        self._fields.0 = Option::Some(value.into());
        PlayFileParamsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: play_file_params_state::State, S: BosStr> PlayFileParamsBuilder<St, S> {
    /// Set the `playerId` field (optional)
    pub fn player_id(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `playerId` field to an Option value (optional)
    pub fn maybe_player_id(mut self, value: Option<S>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St, S: BosStr> PlayFileParamsBuilder<St, S>
where
    St: play_file_params_state::State,
    St::FileId: play_file_params_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> PlayFileParams<S> {
        PlayFileParams {
            file_id: self._fields.0.unwrap(),
            player_id: self._fields.1,
        }
    }
}
