// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.player.seek
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct SeekParams<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub player_id: Option<S>,
    pub position: i64,
}

/** Request marker for the `app.rocksky.player.seek` procedure.

This endpoint has no request parameters or input body; send this marker with `jacquard::Client`.*/

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Copy)]
pub struct Seek;
/** Response marker for the `app.rocksky.player.seek` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `()` for this endpoint.*/
pub struct SeekResponse;
impl jacquard_common::xrpc::XrpcResp for SeekResponse {
    const NSID: &'static str = "app.rocksky.player.seek";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = ();
    type Err = jacquard_common::xrpc::GenericError;
}

impl jacquard_common::xrpc::XrpcRequest for Seek {
    const NSID: &'static str = "app.rocksky.player.seek";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Response = SeekResponse;
}

/** Endpoint marker for the `app.rocksky.player.seek` procedure.

Path: `/xrpc/app.rocksky.player.seek`. The request payload type is `Seek`; use this marker with lower-level `XrpcEndpoint` APIs when you need endpoint metadata.*/
pub struct SeekRequest;
impl jacquard_common::xrpc::XrpcEndpoint for SeekRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.player.seek";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Request<S: BosStr> = Seek;
    type Response = SeekResponse;
}

pub mod seek_params_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Position;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Position = Unset;
    }
    ///State transition - sets the `position` field to Set
    pub struct SetPosition<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetPosition<St> {}
    impl<St: State> State for SetPosition<St> {
        type Position = Set<members::position>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `position` field
        pub struct position(());
    }
}

/// Builder for constructing an instance of this type.
pub struct SeekParamsBuilder<St: seek_params_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>, Option<i64>),
    _type: PhantomData<fn() -> S>,
}

impl SeekParams<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> SeekParamsBuilder<seek_params_state::Empty, DefaultStr> {
        SeekParamsBuilder::new()
    }
}

impl<S: BosStr> SeekParams<S> {
    /// Create a new builder for this type
    pub fn builder() -> SeekParamsBuilder<seek_params_state::Empty, S> {
        SeekParamsBuilder::builder()
    }
}

impl SeekParamsBuilder<seek_params_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        SeekParamsBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> SeekParamsBuilder<seek_params_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        SeekParamsBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<St: seek_params_state::State, S: BosStr> SeekParamsBuilder<St, S> {
    /// Set the `playerId` field (optional)
    pub fn player_id(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `playerId` field to an Option value (optional)
    pub fn maybe_player_id(mut self, value: Option<S>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St, S: BosStr> SeekParamsBuilder<St, S>
where
    St: seek_params_state::State,
    St::Position: seek_params_state::IsUnset,
{
    /// Set the `position` field (required)
    pub fn position(
        mut self,
        value: impl Into<i64>,
    ) -> SeekParamsBuilder<seek_params_state::SetPosition<St>, S> {
        self._fields.1 = Option::Some(value.into());
        SeekParamsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> SeekParamsBuilder<St, S>
where
    St: seek_params_state::State,
    St::Position: seek_params_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> SeekParams<S> {
        SeekParams {
            player_id: self._fields.0,
            position: self._fields.1.unwrap(),
        }
    }
}
