// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.equalizer.putPreset
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::app_rocksky::equalizer::PresetView;
use crate::app_rocksky::rockbox::EqualizerBand;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct PutPreset<S: BosStr = DefaultStr> {
    ///Up to 10 EQ bands
    pub bands: Vec<EqualizerBand<S>>,
    ///Display name of the preset.
    pub name: S,
    ///Pre-amplification cut in tenths of dB applied before EQ bands (e.g. -60 = -6.0 dB)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub precut: Option<i64>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct PutPresetOutput<S: BosStr = DefaultStr> {
    #[serde(flatten)]
    pub value: PresetView<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.rocksky.equalizer.putPreset` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `PutPresetOutput<S>` for this endpoint.*/
pub struct PutPresetResponse;
impl jacquard_common::xrpc::XrpcResp for PutPresetResponse {
    const NSID: &'static str = "app.rocksky.equalizer.putPreset";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = PutPresetOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for PutPreset<S> {
    const NSID: &'static str = "app.rocksky.equalizer.putPreset";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Response = PutPresetResponse;
}

/** Endpoint marker for the `app.rocksky.equalizer.putPreset` procedure.

Path: `/xrpc/app.rocksky.equalizer.putPreset`. The request payload type is `PutPreset<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct PutPresetRequest;
impl jacquard_common::xrpc::XrpcEndpoint for PutPresetRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.equalizer.putPreset";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Request<S: BosStr> = PutPreset<S>;
    type Response = PutPresetResponse;
}

pub mod put_preset_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Bands;
        type Name;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Bands = Unset;
        type Name = Unset;
    }
    ///State transition - sets the `bands` field to Set
    pub struct SetBands<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetBands<St> {}
    impl<St: State> State for SetBands<St> {
        type Bands = Set<members::bands>;
        type Name = St::Name;
    }
    ///State transition - sets the `name` field to Set
    pub struct SetName<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetName<St> {}
    impl<St: State> State for SetName<St> {
        type Bands = St::Bands;
        type Name = Set<members::name>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `bands` field
        pub struct bands(());
        ///Marker type for the `name` field
        pub struct name(());
    }
}

/// Builder for constructing an instance of this type.
pub struct PutPresetBuilder<St: put_preset_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<Vec<EqualizerBand<S>>>, Option<S>, Option<i64>),
    _type: PhantomData<fn() -> S>,
}

impl PutPreset<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> PutPresetBuilder<put_preset_state::Empty, DefaultStr> {
        PutPresetBuilder::new()
    }
}

impl<S: BosStr> PutPreset<S> {
    /// Create a new builder for this type
    pub fn builder() -> PutPresetBuilder<put_preset_state::Empty, S> {
        PutPresetBuilder::builder()
    }
}

impl PutPresetBuilder<put_preset_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        PutPresetBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> PutPresetBuilder<put_preset_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        PutPresetBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> PutPresetBuilder<St, S>
where
    St: put_preset_state::State,
    St::Bands: put_preset_state::IsUnset,
{
    /// Set the `bands` field (required)
    pub fn bands(
        mut self,
        value: impl Into<Vec<EqualizerBand<S>>>,
    ) -> PutPresetBuilder<put_preset_state::SetBands<St>, S> {
        self._fields.0 = Option::Some(value.into());
        PutPresetBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> PutPresetBuilder<St, S>
where
    St: put_preset_state::State,
    St::Name: put_preset_state::IsUnset,
{
    /// Set the `name` field (required)
    pub fn name(
        mut self,
        value: impl Into<S>,
    ) -> PutPresetBuilder<put_preset_state::SetName<St>, S> {
        self._fields.1 = Option::Some(value.into());
        PutPresetBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: put_preset_state::State, S: BosStr> PutPresetBuilder<St, S> {
    /// Set the `precut` field (optional)
    pub fn precut(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `precut` field to an Option value (optional)
    pub fn maybe_precut(mut self, value: Option<i64>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St, S: BosStr> PutPresetBuilder<St, S>
where
    St: put_preset_state::State,
    St::Bands: put_preset_state::IsSet,
    St::Name: put_preset_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> PutPreset<S> {
        PutPreset {
            bands: self._fields.0.unwrap(),
            name: self._fields.1.unwrap(),
            precut: self._fields.2,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> PutPreset<S> {
        PutPreset {
            bands: self._fields.0.unwrap(),
            name: self._fields.1.unwrap(),
            precut: self._fields.2,
            extra_data: Some(extra_data),
        }
    }
}
