// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.playlist.addSongs
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::AtUri;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct AddSongsParams<S: BosStr = DefaultStr> {
    pub songs: Vec<AtUri<S>>,
    pub uri: AtUri<S>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct AddSongsOutput<S: BosStr = DefaultStr> {
    ///AT-URIs of the created app.rocksky.playlist.song records
    pub uris: Vec<AtUri<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Request marker for the `app.rocksky.playlist.addSongs` procedure.

This endpoint has no request parameters or input body; send this marker with `jacquard::Client`.*/

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Copy)]
pub struct AddSongs;
/** Response marker for the `app.rocksky.playlist.addSongs` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `AddSongsOutput<S>` for this endpoint.*/
pub struct AddSongsResponse;
impl jacquard_common::xrpc::XrpcResp for AddSongsResponse {
    const NSID: &'static str = "app.rocksky.playlist.addSongs";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = AddSongsOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl jacquard_common::xrpc::XrpcRequest for AddSongs {
    const NSID: &'static str = "app.rocksky.playlist.addSongs";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Response = AddSongsResponse;
}

/** Endpoint marker for the `app.rocksky.playlist.addSongs` procedure.

Path: `/xrpc/app.rocksky.playlist.addSongs`. The request payload type is `AddSongs`; use this marker with lower-level `XrpcEndpoint` APIs when you need endpoint metadata.*/
pub struct AddSongsRequest;
impl jacquard_common::xrpc::XrpcEndpoint for AddSongsRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.playlist.addSongs";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Request<S: BosStr> = AddSongs;
    type Response = AddSongsResponse;
}

pub mod add_songs_params_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Songs;
        type Uri;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Songs = Unset;
        type Uri = Unset;
    }
    ///State transition - sets the `songs` field to Set
    pub struct SetSongs<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetSongs<St> {}
    impl<St: State> State for SetSongs<St> {
        type Songs = Set<members::songs>;
        type Uri = St::Uri;
    }
    ///State transition - sets the `uri` field to Set
    pub struct SetUri<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetUri<St> {}
    impl<St: State> State for SetUri<St> {
        type Songs = St::Songs;
        type Uri = Set<members::uri>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `songs` field
        pub struct songs(());
        ///Marker type for the `uri` field
        pub struct uri(());
    }
}

/// Builder for constructing an instance of this type.
pub struct AddSongsParamsBuilder<St: add_songs_params_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<Vec<AtUri<S>>>, Option<AtUri<S>>),
    _type: PhantomData<fn() -> S>,
}

impl AddSongsParams<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> AddSongsParamsBuilder<add_songs_params_state::Empty, DefaultStr> {
        AddSongsParamsBuilder::new()
    }
}

impl<S: BosStr> AddSongsParams<S> {
    /// Create a new builder for this type
    pub fn builder() -> AddSongsParamsBuilder<add_songs_params_state::Empty, S> {
        AddSongsParamsBuilder::builder()
    }
}

impl AddSongsParamsBuilder<add_songs_params_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        AddSongsParamsBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> AddSongsParamsBuilder<add_songs_params_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        AddSongsParamsBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> AddSongsParamsBuilder<St, S>
where
    St: add_songs_params_state::State,
    St::Songs: add_songs_params_state::IsUnset,
{
    /// Set the `songs` field (required)
    pub fn songs(
        mut self,
        value: impl Into<Vec<AtUri<S>>>,
    ) -> AddSongsParamsBuilder<add_songs_params_state::SetSongs<St>, S> {
        self._fields.0 = Option::Some(value.into());
        AddSongsParamsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> AddSongsParamsBuilder<St, S>
where
    St: add_songs_params_state::State,
    St::Uri: add_songs_params_state::IsUnset,
{
    /// Set the `uri` field (required)
    pub fn uri(
        mut self,
        value: impl Into<AtUri<S>>,
    ) -> AddSongsParamsBuilder<add_songs_params_state::SetUri<St>, S> {
        self._fields.1 = Option::Some(value.into());
        AddSongsParamsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> AddSongsParamsBuilder<St, S>
where
    St: add_songs_params_state::State,
    St::Songs: add_songs_params_state::IsSet,
    St::Uri: add_songs_params_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> AddSongsParams<S> {
        AddSongsParams {
            songs: self._fields.0.unwrap(),
            uri: self._fields.1.unwrap(),
        }
    }
}
