// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.playlist.removeTrack
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::AtUri;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct RemoveTrackParams<S: BosStr = DefaultStr> {
    /// (min: 0)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub index: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub song_uri: Option<AtUri<S>>,
    pub uri: AtUri<S>,
}

/** Request marker for the `app.rocksky.playlist.removeTrack` procedure.

This endpoint has no request parameters or input body; send this marker with `jacquard::Client`.*/

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Copy)]
pub struct RemoveTrack;
/** Response marker for the `app.rocksky.playlist.removeTrack` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `()` for this endpoint.*/
pub struct RemoveTrackResponse;
impl jacquard_common::xrpc::XrpcResp for RemoveTrackResponse {
    const NSID: &'static str = "app.rocksky.playlist.removeTrack";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = ();
    type Err = jacquard_common::xrpc::GenericError;
}

impl jacquard_common::xrpc::XrpcRequest for RemoveTrack {
    const NSID: &'static str = "app.rocksky.playlist.removeTrack";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Response = RemoveTrackResponse;
}

/** Endpoint marker for the `app.rocksky.playlist.removeTrack` procedure.

Path: `/xrpc/app.rocksky.playlist.removeTrack`. The request payload type is `RemoveTrack`; use this marker with lower-level `XrpcEndpoint` APIs when you need endpoint metadata.*/
pub struct RemoveTrackRequest;
impl jacquard_common::xrpc::XrpcEndpoint for RemoveTrackRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.playlist.removeTrack";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Request<S: BosStr> = RemoveTrack;
    type Response = RemoveTrackResponse;
}

pub mod remove_track_params_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Uri;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Uri = Unset;
    }
    ///State transition - sets the `uri` field to Set
    pub struct SetUri<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetUri<St> {}
    impl<St: State> State for SetUri<St> {
        type Uri = Set<members::uri>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `uri` field
        pub struct uri(());
    }
}

/// Builder for constructing an instance of this type.
pub struct RemoveTrackParamsBuilder<St: remove_track_params_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<i64>, Option<AtUri<S>>, Option<AtUri<S>>),
    _type: PhantomData<fn() -> S>,
}

impl RemoveTrackParams<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> RemoveTrackParamsBuilder<remove_track_params_state::Empty, DefaultStr> {
        RemoveTrackParamsBuilder::new()
    }
}

impl<S: BosStr> RemoveTrackParams<S> {
    /// Create a new builder for this type
    pub fn builder() -> RemoveTrackParamsBuilder<remove_track_params_state::Empty, S> {
        RemoveTrackParamsBuilder::builder()
    }
}

impl RemoveTrackParamsBuilder<remove_track_params_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        RemoveTrackParamsBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> RemoveTrackParamsBuilder<remove_track_params_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        RemoveTrackParamsBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: remove_track_params_state::State, S: BosStr> RemoveTrackParamsBuilder<St, S> {
    /// Set the `index` field (optional)
    pub fn index(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `index` field to an Option value (optional)
    pub fn maybe_index(mut self, value: Option<i64>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St: remove_track_params_state::State, S: BosStr> RemoveTrackParamsBuilder<St, S> {
    /// Set the `songUri` field (optional)
    pub fn song_uri(mut self, value: impl Into<Option<AtUri<S>>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `songUri` field to an Option value (optional)
    pub fn maybe_song_uri(mut self, value: Option<AtUri<S>>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St, S: BosStr> RemoveTrackParamsBuilder<St, S>
where
    St: remove_track_params_state::State,
    St::Uri: remove_track_params_state::IsUnset,
{
    /// Set the `uri` field (required)
    pub fn uri(
        mut self,
        value: impl Into<AtUri<S>>,
    ) -> RemoveTrackParamsBuilder<remove_track_params_state::SetUri<St>, S> {
        self._fields.2 = Option::Some(value.into());
        RemoveTrackParamsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> RemoveTrackParamsBuilder<St, S>
where
    St: remove_track_params_state::State,
    St::Uri: remove_track_params_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> RemoveTrackParams<S> {
        RemoveTrackParams {
            index: self._fields.0,
            song_uri: self._fields.1,
            uri: self._fields.2.unwrap(),
        }
    }
}
