// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.artist.getArtistTracks
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::app_rocksky::song::SongViewBasic;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::AtUri;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetArtistTracks<S: BosStr = DefaultStr> {
    /// (min: 1)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// (min: 0)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uri: Option<AtUri<S>>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetArtistTracksOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tracks: Option<Vec<SongViewBasic<S>>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.rocksky.artist.getArtistTracks` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetArtistTracksOutput<S>` for this endpoint.*/
pub struct GetArtistTracksResponse;
impl jacquard_common::xrpc::XrpcResp for GetArtistTracksResponse {
    const NSID: &'static str = "app.rocksky.artist.getArtistTracks";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetArtistTracksOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetArtistTracks<S> {
    const NSID: &'static str = "app.rocksky.artist.getArtistTracks";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetArtistTracksResponse;
}

/** Endpoint marker for the `app.rocksky.artist.getArtistTracks` query.

Path: `/xrpc/app.rocksky.artist.getArtistTracks`. The request payload type is `GetArtistTracks<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetArtistTracksRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetArtistTracksRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.artist.getArtistTracks";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetArtistTracks<S>;
    type Response = GetArtistTracksResponse;
}

pub mod get_artist_tracks_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type.
pub struct GetArtistTracksBuilder<St: get_artist_tracks_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<i64>, Option<i64>, Option<AtUri<S>>),
    _type: PhantomData<fn() -> S>,
}

impl GetArtistTracks<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GetArtistTracksBuilder<get_artist_tracks_state::Empty, DefaultStr> {
        GetArtistTracksBuilder::new()
    }
}

impl<S: BosStr> GetArtistTracks<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetArtistTracksBuilder<get_artist_tracks_state::Empty, S> {
        GetArtistTracksBuilder::builder()
    }
}

impl GetArtistTracksBuilder<get_artist_tracks_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetArtistTracksBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GetArtistTracksBuilder<get_artist_tracks_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetArtistTracksBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: get_artist_tracks_state::State, S: BosStr> GetArtistTracksBuilder<St, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St: get_artist_tracks_state::State, S: BosStr> GetArtistTracksBuilder<St, S> {
    /// Set the `offset` field (optional)
    pub fn offset(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `offset` field to an Option value (optional)
    pub fn maybe_offset(mut self, value: Option<i64>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St: get_artist_tracks_state::State, S: BosStr> GetArtistTracksBuilder<St, S> {
    /// Set the `uri` field (optional)
    pub fn uri(mut self, value: impl Into<Option<AtUri<S>>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `uri` field to an Option value (optional)
    pub fn maybe_uri(mut self, value: Option<AtUri<S>>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St, S: BosStr> GetArtistTracksBuilder<St, S>
where
    St: get_artist_tracks_state::State,
{
    /// Build the final struct.
    pub fn build(self) -> GetArtistTracks<S> {
        GetArtistTracks {
            limit: self._fields.0,
            offset: self._fields.1,
            uri: self._fields.2,
        }
    }
}
