// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.charts.getTopScrobblers
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::app_rocksky::charts::ScrobblerViewBasic;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::Datetime;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct GetTopScrobblers {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_date: Option<Datetime>,
    /// (min: 1)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// (min: 0)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start_date: Option<Datetime>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetTopScrobblersOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scrobblers: Option<Vec<ScrobblerViewBasic<S>>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.rocksky.charts.getTopScrobblers` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetTopScrobblersOutput<S>` for this endpoint.*/
pub struct GetTopScrobblersResponse;
impl jacquard_common::xrpc::XrpcResp for GetTopScrobblersResponse {
    const NSID: &'static str = "app.rocksky.charts.getTopScrobblers";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetTopScrobblersOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl jacquard_common::xrpc::XrpcRequest for GetTopScrobblers {
    const NSID: &'static str = "app.rocksky.charts.getTopScrobblers";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetTopScrobblersResponse;
}

/** Endpoint marker for the `app.rocksky.charts.getTopScrobblers` query.

Path: `/xrpc/app.rocksky.charts.getTopScrobblers`. The request payload type is `GetTopScrobblers`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetTopScrobblersRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetTopScrobblersRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.charts.getTopScrobblers";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetTopScrobblers;
    type Response = GetTopScrobblersResponse;
}

pub mod get_top_scrobblers_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type.
pub struct GetTopScrobblersBuilder<St: get_top_scrobblers_state::State> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<Datetime>, Option<i64>, Option<i64>, Option<Datetime>),
}

impl GetTopScrobblers {
    /// Create a new builder for this type.
    pub fn new() -> GetTopScrobblersBuilder<get_top_scrobblers_state::Empty> {
        GetTopScrobblersBuilder::new()
    }
}

impl GetTopScrobblersBuilder<get_top_scrobblers_state::Empty> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetTopScrobblersBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
        }
    }
}

impl GetTopScrobblersBuilder<get_top_scrobblers_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetTopScrobblersBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
        }
    }
}

impl<St: get_top_scrobblers_state::State> GetTopScrobblersBuilder<St> {
    /// Set the `endDate` field (optional)
    pub fn end_date(mut self, value: impl Into<Option<Datetime>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `endDate` field to an Option value (optional)
    pub fn maybe_end_date(mut self, value: Option<Datetime>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St: get_top_scrobblers_state::State> GetTopScrobblersBuilder<St> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St: get_top_scrobblers_state::State> GetTopScrobblersBuilder<St> {
    /// Set the `offset` field (optional)
    pub fn offset(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `offset` field to an Option value (optional)
    pub fn maybe_offset(mut self, value: Option<i64>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St: get_top_scrobblers_state::State> GetTopScrobblersBuilder<St> {
    /// Set the `startDate` field (optional)
    pub fn start_date(mut self, value: impl Into<Option<Datetime>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `startDate` field to an Option value (optional)
    pub fn maybe_start_date(mut self, value: Option<Datetime>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<St> GetTopScrobblersBuilder<St>
where
    St: get_top_scrobblers_state::State,
{
    /// Build the final struct.
    pub fn build(self) -> GetTopScrobblers {
        GetTopScrobblers {
            end_date: self._fields.0,
            limit: self._fields.1,
            offset: self._fields.2,
            start_date: self._fields.3,
        }
    }
}
