// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.charts.getScrobblesChart
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::app_rocksky::charts::ChartsView;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::ident::AtIdentifier;
use jacquard_common::types::string::AtUri;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetScrobblesChart<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub albumuri: Option<AtUri<S>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub artisturi: Option<AtUri<S>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub did: Option<AtIdentifier<S>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub from: Option<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub genre: Option<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub songuri: Option<AtUri<S>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub to: Option<S>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetScrobblesChartOutput<S: BosStr = DefaultStr> {
    #[serde(flatten)]
    pub value: ChartsView<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.rocksky.charts.getScrobblesChart` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetScrobblesChartOutput<S>` for this endpoint.*/
pub struct GetScrobblesChartResponse;
impl jacquard_common::xrpc::XrpcResp for GetScrobblesChartResponse {
    const NSID: &'static str = "app.rocksky.charts.getScrobblesChart";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetScrobblesChartOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetScrobblesChart<S> {
    const NSID: &'static str = "app.rocksky.charts.getScrobblesChart";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetScrobblesChartResponse;
}

/** Endpoint marker for the `app.rocksky.charts.getScrobblesChart` query.

Path: `/xrpc/app.rocksky.charts.getScrobblesChart`. The request payload type is `GetScrobblesChart<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetScrobblesChartRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetScrobblesChartRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.charts.getScrobblesChart";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetScrobblesChart<S>;
    type Response = GetScrobblesChartResponse;
}

pub mod get_scrobbles_chart_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type.
pub struct GetScrobblesChartBuilder<St: get_scrobbles_chart_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<AtUri<S>>,
        Option<AtUri<S>>,
        Option<AtIdentifier<S>>,
        Option<S>,
        Option<S>,
        Option<AtUri<S>>,
        Option<S>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl GetScrobblesChart<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GetScrobblesChartBuilder<get_scrobbles_chart_state::Empty, DefaultStr> {
        GetScrobblesChartBuilder::new()
    }
}

impl<S: BosStr> GetScrobblesChart<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetScrobblesChartBuilder<get_scrobbles_chart_state::Empty, S> {
        GetScrobblesChartBuilder::builder()
    }
}

impl GetScrobblesChartBuilder<get_scrobbles_chart_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetScrobblesChartBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GetScrobblesChartBuilder<get_scrobbles_chart_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetScrobblesChartBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: get_scrobbles_chart_state::State, S: BosStr> GetScrobblesChartBuilder<St, S> {
    /// Set the `albumuri` field (optional)
    pub fn albumuri(mut self, value: impl Into<Option<AtUri<S>>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `albumuri` field to an Option value (optional)
    pub fn maybe_albumuri(mut self, value: Option<AtUri<S>>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St: get_scrobbles_chart_state::State, S: BosStr> GetScrobblesChartBuilder<St, S> {
    /// Set the `artisturi` field (optional)
    pub fn artisturi(mut self, value: impl Into<Option<AtUri<S>>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `artisturi` field to an Option value (optional)
    pub fn maybe_artisturi(mut self, value: Option<AtUri<S>>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St: get_scrobbles_chart_state::State, S: BosStr> GetScrobblesChartBuilder<St, S> {
    /// Set the `did` field (optional)
    pub fn did(mut self, value: impl Into<Option<AtIdentifier<S>>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `did` field to an Option value (optional)
    pub fn maybe_did(mut self, value: Option<AtIdentifier<S>>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St: get_scrobbles_chart_state::State, S: BosStr> GetScrobblesChartBuilder<St, S> {
    /// Set the `from` field (optional)
    pub fn from(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `from` field to an Option value (optional)
    pub fn maybe_from(mut self, value: Option<S>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<St: get_scrobbles_chart_state::State, S: BosStr> GetScrobblesChartBuilder<St, S> {
    /// Set the `genre` field (optional)
    pub fn genre(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.4 = value.into();
        self
    }
    /// Set the `genre` field to an Option value (optional)
    pub fn maybe_genre(mut self, value: Option<S>) -> Self {
        self._fields.4 = value;
        self
    }
}

impl<St: get_scrobbles_chart_state::State, S: BosStr> GetScrobblesChartBuilder<St, S> {
    /// Set the `songuri` field (optional)
    pub fn songuri(mut self, value: impl Into<Option<AtUri<S>>>) -> Self {
        self._fields.5 = value.into();
        self
    }
    /// Set the `songuri` field to an Option value (optional)
    pub fn maybe_songuri(mut self, value: Option<AtUri<S>>) -> Self {
        self._fields.5 = value;
        self
    }
}

impl<St: get_scrobbles_chart_state::State, S: BosStr> GetScrobblesChartBuilder<St, S> {
    /// Set the `to` field (optional)
    pub fn to(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.6 = value.into();
        self
    }
    /// Set the `to` field to an Option value (optional)
    pub fn maybe_to(mut self, value: Option<S>) -> Self {
        self._fields.6 = value;
        self
    }
}

impl<St, S: BosStr> GetScrobblesChartBuilder<St, S>
where
    St: get_scrobbles_chart_state::State,
{
    /// Build the final struct.
    pub fn build(self) -> GetScrobblesChart<S> {
        GetScrobblesChart {
            albumuri: self._fields.0,
            artisturi: self._fields.1,
            did: self._fields.2,
            from: self._fields.3,
            genre: self._fields.4,
            songuri: self._fields.5,
            to: self._fields.6,
        }
    }
}
